### ISSUE TITLE
Operatorhub still at v0.39.4

### ISSUE THREAD

**Issue by depouill** [VictoriaMetrics/operator#1003]
Hello,

We are using VictoriaMetrics on Openshift Clusters via OperatorHub OLM subscription. We would like to use VMScrapeConfig CRD available in 0.43 release to Scrape external prometheis. OperatoHub provides only 0.39.4.

Is there any plan to provide more recent releases on OperatorHub to be able to use OLM ?

Thank-you very much,

Philippe

**Comment by f41gh7** [comment]
Hello, 

 Currently, there is no automated pipeline for OLM updates. We're going to publish current and the next release to it soon.

 @Haleygo  PTAL

**Comment by depouill** [comment]
> Hello,
> 
> Currently, there is no automated pipeline for OLM updates. We're going to publish current and the next release to it soon.
> 
> @Haleygo PTAL

Thank-you very much,

Philippe
