### ISSUE TITLE
`targetPort` dropped from endpoints when converting prometheus operator CRs

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/operator#1015]
Looks like when the converters code was moved this was dropped: https://github.com/VictoriaMetrics/operator/blob/5cef723d3ef62b86ebf4e651bcf4b11c5106c650/controllers/converter/apis.go#L350

**Comment by f41gh7** [comment]
It was dropped at the following commit a5d295b

Will be returned back at 0.46.2

**Comment by f41gh7** [comment]
Issue was fixed at [v0.46.2](https://github.com/VictoriaMetrics/operator/releases/tag/v0.46.2) release
