### ISSUE TITLE
Mention source of the docs at https://docs.victoriametrics.com/

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/operator#1018]
The docs in this repo are periodically synced to https://docs.victoriametrics.com/operator.
But those docs do not contain a mention about the source of the docs. So users mistakenly can propose changes to https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/docs/operator. When they should propose the changes to https://github.com/VictoriaMetrics/operator. 

Would be great if these auto-synced docs contained a comment explaining the source of truth for operator docs.

**Comment by AndrewChubatiuk** [comment]
it was fixed at vmdocs repo
