### ISSUE TITLE
Starting from v0.46.0, the Release files are missing bundle_crd.zip.

### ISSUE THREAD

**Issue by hansedong** [VictoriaMetrics/operator#1021]
I found that bundle_crd.zip is missing in the latest Release. I want to confirm, is this intentional or is there an oversight?

**Comment by Haleygo** [comment]
Hi,
it was removed in https://github.com/VictoriaMetrics/operator/commit/a5d295ba68c19cdfcb5cab6c47d8e103972e1278, but this breaks our installation [instruction](https://github.com/VictoriaMetrics/operator/blob/master/docs/setup.md#installing-by-manifest), seems like we need to add it back.
cc @AndrewChubatiuk

**Comment by AndrewChubatiuk** [comment]
will add it soon

**Comment by AndrewChubatiuk** [comment]
hey @hansedong
which content from bundle_crd.zip are you using?

**Comment by hansedong** [comment]
> hey @hansedong which content from bundle_crd.zip are you using?

I personally prefer to use `Manifest` for installation. In the document, there are mentioned operation steps involving the file `bundle_crd.zip`.

```shell
export VM_VERSION=`basename $(curl -fs -o/dev/null -w %{redirect_url} https://github.com/VictoriaMetrics/operator/releases/latest)`
wget https://github.com/VictoriaMetrics/operator/releases/download/$VM_VERSION/bundle_crd.zip
unzip  bundle_crd.zip
```

Will it be changed to using Helm or Kustomize for installation in the future?

**Comment by AndrewChubatiuk** [comment]
[helm](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator) chart is available, kustomize changes are in progress
