### ISSUE TITLE
vmagent: create shard sevices when using vmagent cluster

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/operator#1022]
When enabling `-promscrape.cluster` in vmagent, it's impossible to know which shard we're using through the general service.
It would be helpful to have a seperate svc created for each shard vmagent deployment.

**Comment by Haleygo** [comment]
Also related to https://github.com/VictoriaMetrics/operator/issues/604

**Comment by f41gh7** [comment]
I don't think that it's useful to have separate service per each shard.

It's already possible to access each shard pod with headless service by corresponding pod name. It requires `statefulMode: true`.

**Comment by f41gh7** [comment]
Closing since proposed changes doesn't look useful.
