### ISSUE TITLE
config-reloader-0.46.x images are not deployed correctly

### ISSUE THREAD

**Issue by ebensom** [VictoriaMetrics/operator#1029]
When using config-reloader images > 0.45.0 (e.g. `config-reloader-0.46.3`), all pods having the VM custom config reloader injected cannot start due to the following configuration error:

```
    state:
      waiting:
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "/usr/local/bin/config-reloader": stat /usr/local/bin/config-reloader:
          no such file or directory: unknown'
        reason: RunContainerError
```

It seems that the container command has not been adjusted to the new path to the application binary. All places with custom config reloader specific logic:
https://github.com/search?q=repo%3AVictoriaMetrics%2Foperator%20UseCustomConfigReloader&type=code

**Comment by f41gh7** [comment]
@AndrewChubatiuk  PTAL
