### ISSUE TITLE
VMCLUSTER not uninstalled when WATCH_NAMESPACE is set 

### ISSUE THREAD

**Issue by vmw-web** [VictoriaMetrics/operator#1036]
1. Set WATCH_NAMESPACE to "test-namespace"
2. Installed the operator with the single namespace RBAC in the namespace "test-namespace" [RBAC](https://github.com/VictoriaMetrics/operator/blob/master/config/examples/operator_rbac_for_single_namespace.yaml)
3. Installed the VMCLUSTER in the namespace "test-namespace", and uninstalled, the VMCLUSTER is not uninstalled completely
4. Operator logs shows RECONCILE ERROR

**Comment by vmw-web** [comment]
Updated the operator image to v0.46.4, and the issue still exists. Cluster components are not deleted.

**Comment by f41gh7** [comment]
> Updated the operator image to v0.46.4, and the issue still exists. Cluster components are not deleted.

An issue will be fixed at the next release

**Comment by f41gh7** [comment]
Bug must be fixed at [v0.47.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.0)
