### ISSUE TITLE
operator: log timestamp format

### ISSUE THREAD

**Issue by olga-larina** [VictoriaMetrics/operator#1037]
Hi.

Is it possible to set timestamp format in the logs for VM operator (for example, ISO8601)? Or customize the logs?

The operator uses zap for logging. Can I use the flag `zap-time-encoding`?

Or it can`t be done after https://github.com/VictoriaMetrics/operator/issues/963 ?

**Comment by f41gh7** [comment]
Hello, it should be already possible with command-line flag `--zap-time-encoding`.

```
--zap-time-encoding time-encoding                  Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.
```

**Comment by olga-larina** [comment]
Thanks.
I see that in [v0.45.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.45.0) were made these changes: "expose only command-line flags related to the operator"
In next versions we can again use other command-line flags? Because I don`t these changes in master.

v0.45.0: 
https://github.com/VictoriaMetrics/operator/blob/310a8600610fd9bca96248c12f25f6895038f6ed/internal/manager/manager.go#L43
https://github.com/VictoriaMetrics/operator/blob/310a8600610fd9bca96248c12f25f6895038f6ed/internal/manager/manager.go#L89

master: 
https://github.com/VictoriaMetrics/operator/blob/ffe2ffbb5f19bd333a86c6a6eca4b11f8bad5ead/internal/manager/manager.go#L88

**Comment by f41gh7** [comment]
> Thanks. I see that in [v0.45.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.45.0) were made these changes: "expose only command-line flags related to the operator" In next versions can we again use other command-line flags? Because I don`t see these changes in master.
> 
> v0.45.0:
> 
> https://github.com/VictoriaMetrics/operator/blob/310a8600610fd9bca96248c12f25f6895038f6ed/internal/manager/manager.go#L43
> 
> https://github.com/VictoriaMetrics/operator/blob/310a8600610fd9bca96248c12f25f6895038f6ed/internal/manager/manager.go#L89
> 
> master:
> 
> https://github.com/VictoriaMetrics/operator/blob/ffe2ffbb5f19bd333a86c6a6eca4b11f8bad5ead/internal/manager/manager.go#L88

 Related commit removed flags exposed by VM transitive dependencies. It's still possible to use any other cmd flags exposed by operator. Such as `--zap-time-encoding`

**Comment by olga-larina** [comment]
Ok, thank you!
