### ISSUE TITLE
VMAuth skip broken VMUsers during config building

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1047]
Currently, a single VMUser with incorrect configuration could break VMAuth config generation.

It must be changed in the same way, as currently handled scrape objects.

It needed because VMUser object could be created by non-owner of VMAuth. 

It'd be great in addition:
- add validation to the webhook configuration (related to the required url related fields)
- add status to the VMUser object
- print summary into operator log

**Comment by AndrewChubatiuk** [comment]
released in [v0.47.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.0)
