### ISSUE TITLE
Add VLogs to the operator API

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1052]
# Goals

* Managed vlogs application by operator.
* Simplified deployment and configuration.

# Implementation details

* Use the same logic that we already have for `VMSingle`. 
* Use `Deployment` with restart strategy `Recreate`. 
* move useful configuration flags into `Spec` field. 
* add ingest ports configuration, such as syslog server.

**Comment by AndrewChubatiuk** [comment]
released in [v0.47.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.0)
