### ISSUE TITLE
Support for topologySpreadConstraints

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#107]
I want support for topologySpreadConstraints in CRs that deploy pods. It makes pod scheduling more flexible.

It is already supported in Prometheus Operator.

**Comment by umezawatakeshi** [comment]
I tried the update #110 .

Because the VMCluster CRD becomes much larger, it now hit the problem stated at https://github.com/kubernetes/kubectl/issues/712 . This problem can be avoided by using server-side apply and the procedure written in [quick-start.MD](https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD) might be updated to use `kubectl apply --server-apply=true`. However, my team uses Argo CD to deploy applications including VictoriaMetrics operator and Argo CD does not support server-side apply yet...

The operator itself seems to be working as expected. Thank you.

**Comment by f41gh7** [comment]
Ahhh, get it. Its a common issue with huge crd objects, i'll fix it soon. 

 But in general need to think about some marker at kubernetes controller-gen, that will skip schema generation for embedded resources.

**Comment by umezawatakeshi** [comment]
I tested v0.5.0. It seems to work fine. Thank you.
