### ISSUE TITLE
v1alpha1.ScrapeConfigSpec metricsPath is not converted

### ISSUE THREAD

**Issue by jfroy** [VictoriaMetrics/operator#1073]
The `metricsPath` field of [v1alpha1.ScrapeConfigSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1alpha1.ScrapeConfigSpec) is not converted by the operator. [v1beta1.VMScrapeConfigSpec](https://docs.victoriametrics.com/operator/api/#vmscrapeconfigspec) has a `path` field, but the operator does not handle the translation.

**Comment by f41gh7** [comment]
Will be fixed as part of upcoming v0.47.1 release

**Comment by f41gh7** [comment]
Issue must be fixed at https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.1 release
