### ISSUE TITLE
Can not create VMUser for VMAlertmanager

### ISSUE THREAD

**Issue by Jack200704** [VictoriaMetrics/operator#1083]
After upgrading to version 0.47, a new `enum` field was added to VMUser to specify the type of crd, which includes `VMAlertManager`. However, the kind of `VMAlertManager` is not `VMAlertManager`, but `VMAlertmanager`. This causes deployment issues for VMUser after the upgrade because it cannot find the corresponding crd to deploy successfully.

If fill in the VMAlertmanager in the targetRefs CRD, the following error occurs:

`The VMUser "vmuser-vmalertmanager" is invalid: spec.targetRefs[0].crd.kind: Unsupported value: "VMAlertmanager": supported values: "VMAgent", "VMAlert", "VMSingle", "VMAlertManager", "VMCluster/vmselect", "VMCluster/vmstorage", "VMCluster/vminsert"`

If fill in VMAlertManager in the targetRefs CRD, it can be deployed normally, but the status will show the following:

```
status:
  lastSyncError: 'unsupported kind for ref: "VMAlertManager" at idx=0'
  status: failed
```

**Comment by f41gh7** [comment]
Issue must be fixed at [v0.47.2](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.2) release
