### ISSUE TITLE
VMAlertmanager: possibility to customize default matcher labels

### ISSUE THREAD

**Issue by romainlaurent** [VictoriaMetrics/operator#1096]
Hey folks

I have my Alert Manager running in a cluster, and it's reading VMAlertmanagerConfig from different namespaces. I could add the namespace label through VMAlert, but the metrics are coming from another cluster, and the namespace would be overwritten even though it's needed in the rule.

Would it be possible to customize the default label matcher by configuring the VMAlertmanager operator? We could change it [here](https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/factory/alertmanager/config.go#L234).

I'd be happy to implement this change if you're okay with it.

**Comment by f41gh7** [comment]
Hello, 

 I don't think, that changing default matcher is a good idea. First of all, it was designed for SaaS like metrics stack deployment. When scraping, alerting and notification configurations created at the same namespace. In this case `namespace` label enforced at `scraping` and `notification` configurations. 

 I'd suggest to disable namespace matcher and add needed matchers manually at `VMAlertmanagerConfig`s. 

 Maybe we could add some sort of `globalVMAlertmanagerConfigMatchers` array at `VMAlertmanager` side.

Like:

```yaml
kind: VMAlertmanager
spec:
  globalVMAlertmanagerConfigMatchers:
   - {namespace != ""}
```
 But it doesn't look like good solution to me.

**Comment by romainlaurent** [comment]
The solution you propose seems to be a good one.
It would allow for better control over the default matchers.

To provide context, I have no control over the `VMAlertmanagerConfigs`, which are configurable by the user.
I do have control over the `VMAlert`, where I can set up static labels, and the `VMAlertmanager` (knowing the alert manager is shared among multiple users).

This feature would help me significantly to avoid alert collisions between users and undesired label overrides.

**Comment by f41gh7** [comment]
Feature added  at [v0.48.3](https://github.com/VictoriaMetrics/operator/releases/tag/v0.48.3) release. 

 With new setting `spec.enforcedTopRouteMatchers` it's possible to enforce matchers for all `VMAlertmanagerConfig` for particular `VMAlertmanager.


```yaml
kind: VMAlertmanager
spec:
  enforcedTopRouteMatchers:
  - {namespace!=""}
```

 Must enforce `namespace` label to present at alert to be able routed into `VMAlertmanagerConfig`.

**Comment by robincw-gr** [comment]
Ok, this allows a fixed matcher to be configured when creating an VMAlertManager, but doesn't help deal with the `namespace` matcher that has the dynamic value for building top-level routes; this label name is [hard-coded](https://github.com/VictoriaMetrics/operator/blob/master/internal/controller/operator/factory/vmalertmanager/config.go#L233).
The very generic `namespace` label name is (ironically!) not namespaced, so it is ambiguous and overloaded; it can be set by users and appear in metrics (used in alert rules) to mean other types of namespaces used in the infrastructure or business domain. In this case we need it to mean "the namespace of the VMAlertManagerConfig that the alert should be routed to", so a better name would be something like "alertmanagerconfig_namespace". But, making it configurable in the operator would be best, or allowing an override for the label name in the VMAlertManagerConfig, e.g. `namespaceLabel: alertmanagerconfig_namespace`?
