### ISSUE TITLE
vmalert.spec support host_aliases

### ISSUE THREAD

**Issue by Wangyiwei-So** [VictoriaMetrics/operator#1099]
### Describe the solution you'd like

I think vmalert.spec can support host_aliases, like vmagent crd.

**Comment by f41gh7** [comment]
Will be fixed at next release.

 Operator will support both spec naming`host_aliases` and `hostAliases`. `host_aliases` has priority over `hostAliases`.

**Comment by f41gh7** [comment]
Inconsistency was fixed  at [v0.48.3](https://github.com/VictoriaMetrics/operator/releases/tag/v0.48.3) release.
