### ISSUE TITLE
configReloaderImageTag,configReloaderResources missing in crd defintion

### ISSUE THREAD

**Issue by rmartinez3** [VictoriaMetrics/operator#1112]
Was looking at api spec to overwrite configRealoder image tag to use. As well wanted to set specific resources for container
I then noticed that operator was not setting things as I wanted. I then saw that overall the crd definition doesn't have it defined in its spec.

https://docs.victoriametrics.com/operator/api/?highlight=configreloaderimagetag#commonconfigreloaderparams

I  was trying to see how to generate crd but seems like its taken by this overlay?
https://github.com/VictoriaMetrics/operator/blob/master/config/crd/overlay/crd.yaml
Unsure if needed to be add there.

configReloaderExtraArgs , seems to be defined at least.

I was looking specifically at vmagent but I think the definition is missing as well on other resources as well (VMAlertSpec,,VMAlertmanagerSpec)

**Comment by f41gh7** [comment]
Hello, it would be possible to set reloader image and resources per CRD at the next operator release. 

 Currently, there is global configuration for operator with the following env variables per resource:
```
VM_VMALERTDEFAULT_CONFIGRELOADERCPU=
VM_VMALERTDEFAULT_CONFIGRELOADERMEMORY=
VM_VMALERTDEFAULT_CONFIGRELOADIMAGE=
VM_VMALERTDEFAULT_USEDEFAULTRESOURCES=
```
https://docs.victoriametrics.com/operator/vars/

**Comment by rmartinez3** [comment]
Got it. So will go with Env Variables route for now .
Will make those changes then on my end and await on the crd resource route when that becomes official route.

Thanks for the info
