### ISSUE TITLE
vmcluster not using global container registry default

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/operator#1118]
It looks like: https://github.com/VictoriaMetrics/operator/blob/d39fc945f57cbf9fa2e5f3bb122bc4c5cc537840/internal/controller/operator/factory/build/defaults.go#L460

is not applied to vmcluster like the other resources which correctly apply the global default

**Comment by f41gh7** [comment]
Thanks for reporting! It'll be fixed soon.

**Comment by f41gh7** [comment]
Issue was fixed at [v0.48.3](https://github.com/VictoriaMetrics/operator/releases/tag/v0.48.3) release.
