### ISSUE TITLE
Incorrect arguments read for TLS in VMCluster

### ISSUE THREAD

**Issue by naveenbharadwaj-nc** [VictoriaMetrics/operator#1122]
Hello,

It seems like there is incorrect logic added as part of this [PR](https://github.com/VictoriaMetrics/operator/pull/1005/files). While obtaining VMInsertURL and VMStorageURL, operator checks for VMSelect extraArgs. It seems incorrect. Could you please fix it?
![image](https://github.com/user-attachments/assets/2cc9bdc7-2939-49bc-84f3-b6af343e4f4c)

**Comment by naveenbharadwaj-nc** [comment]
Could you please release the fix ASAP?

**Comment by f41gh7** [comment]
Issue must be fixed at [v0.48.4](https://github.com/VictoriaMetrics/operator/releases/tag/v0.48.4) release
