### ISSUE TITLE
vmauth: add ability to provide external configuration via Vault Sidecar

### ISSUE THREAD

**Issue by AndrewChubatiuk** [VictoriaMetrics/operator#1125]
Currently VMAuth supports configuration management via:
- config-reloader 
- externally managed kubernetes secrets
[Vault Sidecar](https://developer.hashicorp.com/vault/docs/platform/k8s/injector) doesn't rely on k8s secrets and renders templates inside pod. Need to disable config-reloader and configuration management via secrets if path to vmauth configuration is set

**Comment by f41gh7** [comment]
Feature included to the [v0.49.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.49.0) release
