### ISSUE TITLE
Unable to install  the newest version of the VMOperator Helm chart/upgrade to it

### ISSUE THREAD

**Issue by MitchIonascu** [VictoriaMetrics/operator#1126]
Hi!

I've been having some issues upgrading from an existing install of the helm chart, version v0.46.4  to the latest v0.48.3.

This issue is also present when trying to install v0.48.3 from scratch.

Error as follows:

`Error: UPGRADE FAILED: template: victoria-metrics-operator/templates/deployment.yaml:36:20: executing "victoria-metrics-operator/templates/deployment.yaml" at <include "vm.image" (dict "helm" . "app" .Values)>: error calling include: template: victoria-metrics-operator/charts/victoria-metrics-common/templates/_image.tpl:22:16: executing "vm.image" at <tpl (printf "%s:%s" .app.image.repository $tag) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: victoriametrics/operator:v0.48.3: "BasePath" is not a value`

I've gone through the latest available values.yaml, and cannot find any discrepancy between my config and the recommended one that could explain the behaviour.

Issue appears to step from _image.tpl

Any help would be greatly appreciated, thanks!

Values.yaml used attached.
[values.zip](https://github.com/user-attachments/files/17268961/values.zip)

**Comment by f41gh7** [comment]
Hello, looks like it's an issue with helm version. And it's required to upgrade helm to the most recent version.

 @AndrewChubatiuk PTAL

**Comment by AndrewChubatiuk** [comment]
hey @MitchIonascu 
helm 3.14+ is required

**Comment by MitchIonascu** [comment]
Thank you very much! I can confirm that it is working now!
