### ISSUE TITLE
Default security context missing in init containers (vmagent)

### ISSUE THREAD

**Issue by deB4SH** [VictoriaMetrics/operator#1134]
Hi there,
the operator is not adding the configured security context towards the initContainer currently, which leads to an issue with updates in our infrastructure.

Seems to be a regression bug following https://github.com/VictoriaMetrics/operator/issues/767 ?

Without the given security context the container is unable to spawn. 

issued: 
![Bildschirmfoto_20241029_102834](https://github.com/user-attachments/assets/80d42aeb-df30-4262-9892-d4f14bacdb41)

expected:
![Bildschirmfoto_20241029_102654](https://github.com/user-attachments/assets/27900883-8ad7-40a8-9db3-2063f3feae39)

current workaround:
We're overlaying the init container currently via the initContainers field. This produces a lot of redundancy when also a security context is configured "globally" within the VMAgent custom ressource.

https://github.com/Hamburg-Port-Authority/kubernetes-service-catalog/commit/1252eb74e740a62fc2cc32860adf9d8f39ebfb7f

**Comment by f41gh7** [comment]
Hello, bug should be fixed since [v0.48.0](https://github.com/VictoriaMetrics/operator/blob/master/docs/CHANGELOG.md#v0480---25-sep-2024) operator release. v0.48.4 also has few improvements to the container security configuration.

**Comment by deB4SH** [comment]
Thanks for the information. We're currently on 0.46.4.
I'm updating to latest and retest again :)

**Comment by deB4SH** [comment]
Hi @f41gh7 - sorry for the late response

Removed our patch and it seems that some information of our securityContext is not applied. 
![image](https://github.com/user-attachments/assets/cb37c575-c0e0-4312-b543-38f6d267acbf)

After adding back the overlayed part it works as expected.

Security Context Source: https://github.com/Hamburg-Port-Authority/kubernetes-service-catalog/blob/fcebe7abd1d0cc8145b1dea0445def14665ded40/monitoring/victoria-metrics-operator-vmagent/templates/vmagent.yaml#L30

**Comment by f41gh7** [comment]
Thanks for reporting! Bug will be fixed at the next release. I'd expect it at the middle of the next week.

**Comment by f41gh7** [comment]
Bug included to the [v0.49.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.49.0) release
