### ISSUE TITLE
Bug: PVC doesn't resize after changing size field in VMSingle

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/operator#1144]
Probably because of this:
https://github.com/VictoriaMetrics/operator/blob/a9007fa56c33d04eeefd6c2f1cfabb3510b9eb60/internal/controller/operator/factory/reconcile/pvc.go#L43

**Comment by f41gh7** [comment]
Bug included to the [v0.49.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.49.0) release
