### ISSUE TITLE
Add support for `loggerJSONFields` 

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/operator#1157]
Reopening this from #963 - which took a wild turn and explicitly removed the option.

I'd still like for the operator to support field remapping like most of VM binaries do. This is necessary to get timestamps int eh correct field names for cloud platforms and logging parsers. (e.g. Google cloud logging / stackdriver).

See #963 for details, but being able to remap the timestamp and message keys in json logs.

**Comment by f41gh7** [comment]
new flag will be added at the upcoming release.

**Comment by f41gh7** [comment]
Issue was fixed at [v0.50.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.50.0) release
