### ISSUE TITLE
Duplicate api groups in cluster role?

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/operator#1167]
Is there any reason for this?

https://github.com/VictoriaMetrics/operator/blob/b3e19a2c7d9eece919839bbb8698bcf0f9703d4b/config/rbac/role.yaml#L305-L309

**Comment by f41gh7** [comment]
I don't think that there is any reason for that. This file should be generate by some `operator-sdk` command based on needed permissions on reconcile controllers.
 Need to fix that. 

 Btw, extensions seems to be deprecated k8s API.

**Comment by uhthomas** [comment]
That's a good point, the extensions API group should be removed too.

**Comment by Haleygo** [comment]
Hi @uhthomas ,
the role yaml has been fixed in https://github.com/VictoriaMetrics/operator/pull/1177, let me know if there is further question.
