### ISSUE TITLE
Support for multiple notifiers in VMAlert CR

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#117]
According to [Alertmanager's README](https://github.com/prometheus/alertmanager/blob/v0.21.0/README.md#high-availability), alert source (Prometheus or vmalert program) should send same alert to all instances in Alertmanager HA cluster. So, it is required to add support for multiple notifiers. vmalert program itself already has this feature.

To handle only single HA cluster, it is enough to add `urls` field in `VMAlertNotifierSpec`. (This is also what I want.)

To use different credentials for different Alertmanagers, it is required to add `notifiers` field in `VMAlertSpec` too. In this case, it is also required to add support for multiple `-notifier.tlsInsecureSkipVerify` options in vmalert program.

**Comment by f41gh7** [comment]
for now `-notifier.tlsInsecureSkipVerify` will be set globally, if one of notifier targets has setting: `insecureSkipVerify: true`.

 I'll fix it at vmalert and include to the next release. 

 I've added  to `VMAlert.Spec.notifiers`.

  Its also possible to use old variant - `VMAlert.Spec.notifier`. It will be joined to notifiers definition as last element.

**Comment by f41gh7** [comment]
partly added to the latest v0.6.0 release!

 Awaiting fix at vmalert side.

**Comment by umezawatakeshi** [comment]
I tested latest v0.6.0. Unfortunately, this version has a crash bug.

If a VMAlert has only `notifiers`, operator crash with following log:
```
E1216 09:24:00.860263       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1203 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15bbfe0, 0x229f8c0)
        k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x15bbfe0, 0x229f8c0)
        runtime/panic.go:969 +0x1b9
github.com/VictoriaMetrics/operator/controllers/factory.loadTLSAssetsForVMAlert(0x196bee0, 0xc000118000, 0x197a4a0, 0xc000998fc0, 0xc00177f400, 0x8fc9f9638d39bde6, 0xc000f9dc80, 0xc001710a40)
        github.com/VictoriaMetrics/operator/controllers/factory/vmalert.go:654 +0x104
github.com/VictoriaMetrics/operator/controllers/factory.CreateOrUpdateTlsAssetsForVMAlert(0x196bee0, 0xc000118000, 0xc00177f400, 0x197a4a0, 0xc000998fc0, 0xc000a86e80, 0x1)
        github.com/VictoriaMetrics/operator/controllers/factory/vmalert.go:612 +0x77
github.com/VictoriaMetrics/operator/controllers/factory.CreateOrUpdateVMAlert(0x196bee0, 0xc000118000, 0xc00177f400, 0x197a4a0, 0xc000998fc0, 0xc0003c4000, 0xc001beb950, 0x1, 0x1, 0x0, ...)
        github.com/VictoriaMetrics/operator/controllers/factory/vmalert.go:120 +0x3bc
github.com/VictoriaMetrics/operator/controllers.(*VMAlertReconciler).Reconcile(0xc000998fc0, 0xc0001185e0, 0xa, 0xc000916e80, 0x12, 0xc001c88160, 0xc000578d80, 0xc000ab8ea8, 0xc000ab8ea0)
        github.com/VictoriaMetrics/operator/controllers/vmalert_controller.go:68 +0x4a7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00015d8c0, 0x1611360, 0xc001c88100, 0xc000066400)
        sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00015d8c0, 0x203000)
        sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00015d8c0)
        sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000de2270)
        k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000de2270, 0x1937520, 0xc0004e8ba0, 0x1, 0xc00040c2a0)
        k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000de2270, 0x3b9aca00, 0x0, 0x181c901, 0xc00040c2a0)
        k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000de2270, 0x3b9aca00, 0xc00040c2a0)
        k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:170 +0x3fa
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13f1e44]
```

This is because `cr.Spec.Notifier` is nil at https://github.com/VictoriaMetrics/operator/blob/v0.6.0/controllers/factory/vmalert.go#L654
In addition, this part doesn't seems to take care of `notifiers`.

**Comment by umezawatakeshi** [comment]
As far as old VMAlert configuration (i.e. having only `notifier`) is used, v0.6.0 seems work fine.

**Comment by f41gh7** [comment]
Thx, need to cover it with testcase. I will release hotfix shortly.

**Comment by f41gh7** [comment]
fixed in master branch.

**Comment by umezawatakeshi** [comment]
Sorry for being late. I tested v0.6.1 and confirmed that the problem is fixed. Thank you.

note: I did not test credential behavior. Just tested multiple notifier URLs.

**Comment by f41gh7** [comment]
Added missing InsecureSkipVerify per notifier. Since [v1.51.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.51.0) vmalert supports it.

**Comment by f41gh7** [comment]
included in release https://github.com/VictoriaMetrics/operator/releases/tag/v0.7.0
