### ISSUE TITLE
license: add `forceOffline` and `reloadInternal` configuration params

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#1182]
VictoriaMetrics enterprise has `license.forceOffline` and `-licenseFile.reloadInterval` configuration parameters. It'd be great to have directly exposed via `license` definition. 

https://docs.victoriametrics.com/enterprise/?highlight=licenseforce#binary-releases

**Comment by AndrewChubatiuk** [comment]
when it's implemented it can already be set once for all CRs managed by k8s-stack chart at `global.license.forceOffline` and `global.license.reloadInterval`
