### ISSUE TITLE
Typo in Field Name in Example Configuration

### ISSUE THREAD

**Issue by SummerSweety** [VictoriaMetrics/operator#1189]
Hello,
I noticed a typo in the example configuration file config/examples/vmcluster_with_service_override.yaml. According to the [VictoriaMetrics Operator API documentation](https://docs.victoriametrics.com/operator/api/#additionalservicespec), the field name should be useAsDefault instead of userAsDefault.
Could you please update the example to reflect the correct field name?
Thank you!

**Comment by f41gh7** [comment]
Issue was fixed at linked PR
