### ISSUE TITLE
The API documentation is a bit broken due to angle brackets

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#119]
For example, the document comment of `Secrets` in `VMAlertSpec` has the sentence `The Secrets are mounted into /etc/vm/secrets/<secret-name>.`. This part is copied into api.MD as-is, so `<secret-name>` is misunderstood as an HTML tags. As a result, it is displayed just as "The Secrets are mounted into /etc/vm/secrets/." and makes no sense.

I first tried to fix this problem just by escaping angle brackets. However, those document comments are also used for field descriptions in CRDs and angle brackets should not be "escaped" in the description. Now I'm not sure what is the best way to fix it.

**Comment by f41gh7** [comment]
Thanks for reporting, i ll take a look.

**Comment by f41gh7** [comment]
should be fixed at branch https://github.com/VictoriaMetrics/operator/blob/fixes-docs-escape/docs/api.MD

This docs are auto-generated by doc-print binary.

**Comment by umezawatakeshi** [comment]
I saw the fix. Seems properly displayed. Thank you.
