### ISSUE TITLE
ConsulSDConfig support for filter field

### ISSUE THREAD

**Issue by spirkaa** [VictoriaMetrics/operator#1196]
In docs https://docs.victoriametrics.com/sd_configs/#consul_sd_configs mentioned, that vmagent supports `filter` field, but operator don't - `operator.victoriametrics.com/v1beta1, Kind=VMScrapeConfig): .spec.consulSDConfigs[0].filter: field not declared in schema.`

Can this support be added?

**Comment by f41gh7** [comment]
The issue was fixed at [v0.51.1](https://github.com/VictoriaMetrics/operator/releases/tag/v0.51.1) release
