### ISSUE TITLE
kubernetes_sd_configs.role: service equivalent

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#127]
I want support for `kubernetes_sd_configs.role: service`. VMServiceScrape is equivalent to `role: endpoints`, not `role: service`.

It is ideal that `VMServiceScrape` is equivalent to `role: service` and `VMEndpointsScrape` is equivalent to `role: endpoints`. However, it's too late to change CR's name. I think that some option to switch `role` will be added to `VMServiceScrape`.

**Comment by f41gh7** [comment]
There is also `role: endpointslices` https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/

 need to think, maybe its possible to add it as well.

**Comment by f41gh7** [comment]
I've added new option to `VMServiceScrapeSpec` - `discoveryRole`. See related PR.

**Comment by f41gh7** [comment]
included in release https://github.com/VictoriaMetrics/operator/releases/tag/v0.7.0

**Comment by umezawatakeshi** [comment]
I tested v0.7.1. It seems to work fine. Thank you.

**Comment by umezawatakeshi** [comment]
By the way, api.MD is not updated yet.

**Comment by f41gh7** [comment]
> By the way, api.MD is not updated yet.

 Thanks, i ll update. And its time to add linter for it.
