### ISSUE TITLE
operator does not take into account deletionTimestamp

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#132]
The operator insists reconciling even if CRs are being deleted. The operator should not do anything for CRs that have deletionTimestamp.

--

I tried to delete a VMSingle which are no longer used in my cluster. Although kubernetes itself tries to automatically delete the descendant objects such as Deployment and Service, the operator detects that they have been deleted and tries to recreate Deployment, so the deletion of the VMSingle could not be completed.

**Comment by f41gh7** [comment]
Thanks, will take a look. Underhood, operator relies on operator-sdk lib, probably bug happens here.  What is your Kubernetes version?

**Comment by umezawatakeshi** [comment]
I use Kubernetes v1.18.9 in my cluster.

**Comment by f41gh7** [comment]
I've added deletion timestamp check.

 But i cannot reproduce it locally.

**Comment by umezawatakeshi** [comment]
Thank you. I will test it after the new year holiday.

**Comment by f41gh7** [comment]
included to release https://github.com/VictoriaMetrics/operator/releases/tag/v0.7.0

**Comment by umezawatakeshi** [comment]
I'm testing v0.7.1. It may taka a while longer to complete because there is something wrong in my cluster environment...

**Comment by umezawatakeshi** [comment]
I could not reproduce the problem with older operator at my cluster either. The problem does not occur with operator v0.7.1, so this issue may be closed.

**Comment by f41gh7** [comment]
Thanks for testing.
 I believe, that it was an issue with some high latency between reconciliation and resource deletion. Any way, operator respects deletion timestamp now. Reopen an issue if it happens again.
