### ISSUE TITLE
VMOperator spawns new VMAlert deployments for every namespace with VMRules

### ISSUE THREAD

**Issue by Blargansmarf** [VictoriaMetrics/operator#140]
VMOperator is spinning up new deployments of VMAlert constantly. We have ~1900 namespaces with ~8700 rules across them. The behaviour we're seeing is that VMAlert is in a constant state of rolling deploy and never actually spins up. The deployments are incrementing multiple times per second. K8s is not terminating the pods based on probes, in fact the deployments are happening so fast that the probes don't have a chance to proc.

As far as I can tell, the vmrule controller is reconciling after every rule group and not letting the pod spin up at all.

Current version of operator: v0.5.0
Current version of everything else: v.1.45.0-cluster
Using OpenShift v3.11 / K8s v1.11

**Comment by f41gh7** [comment]
Thanks for reporting, in your setup you have one `VMAlert` per namespace or its spited among them somehow? And another question, can you make diff for deployment to detect which part was changed, it helps a lot. With something like:
```bash
kubectl get deployment vmalert-deploy-name -o yaml > /tmp/v1 && sleep 1 && kubectl get deployment  vmalert-deploy-name  -o yam > /tmp/v2 && diff /tmp/v2 /tmp/v1
```

**Comment by f41gh7** [comment]
An issue must be fixed in related PR.

 Also, i've built hot-fix version for v0.5.0, its available at branch https://github.com/VictoriaMetrics/operator/tree/v0.5.1-vmalert-fix
or via docker image `victoriametrics/operator:v0.5.1-hot-fix`

**Comment by c10l** [comment]
@f41gh7 I'm not OP but was facing the same issue. I've manually built the `fixes-vmalert-deployment` branch and it makes the problem go away.

Are you planning to release a new version with the patch on top of `0.7.0` soon?

**Comment by f41gh7** [comment]
Yep, going to tag it tomorrow.  I found another small issue with rules configmap deletion/creation instead of updating it and changed behavior. 

  Changes included in  PRs branch and available at docker image `victoriametrics/operator:fixes-vmalert-deployment`

**Comment by Blargansmarf** [comment]
That's awesome, thanks for looking into and fixing the issue so quickly. Won't be able to validate for myself until next week but I'll take @c10l 's word for it right now.

**Comment by f41gh7** [comment]
fix was included to https://github.com/VictoriaMetrics/operator/releases/tag/v0.7.1 release.
