### ISSUE TITLE
servername in tlsconfig missing

### ISSUE THREAD

**Issue by tesharp** [VictoriaMetrics/operator#144]
https://github.com/VictoriaMetrics/operator/blob/fbaa76f41f5bc8c3ac59a1ec3873a466380b0427/controllers/converter/apis.go#L149

It seems the serverName is in the type definition, but not mapped in convert method. So its never set in VMServiceScrape.

**Comment by f41gh7** [comment]
Thanks for reporting! Must be fixed at master branch, i'm going to make minor release soon.

**Comment by f41gh7** [comment]
fix was included to https://github.com/VictoriaMetrics/operator/releases/tag/v0.7.2 release
