### ISSUE TITLE
Add tlsconfig to VMServiceScrape when creating VMCluster

### ISSUE THREAD

**Issue by tesharp** [VictoriaMetrics/operator#146]
Creating a VMCluster inside an istio service mesh and need to add tlsconfig to the VMServiceScrape endpoint to be able to scrape the services. However does not seem to be any way to add any overrides to the VMServiceScrape created by cluster.

Could it be possible to add tlsconfig to the scrape endpoint? Need it globally on all self registered VMServiceScrape

**Comment by f41gh7** [comment]
I can suggest two options:

1) patch created resources with kubectl patch command - to add needed config. Its not reconciled, so changes must be kept. 

2) set variable for operator `VM_DISABLESELFSERVICESCRAPECREATION=true`, remove created by operator `VMServiceScrape` and create new `VMServiceScrape` with needed config separately. 

 I don't see any good option to manage it from operator side. Embedding it to CRD seems to be bad solution - its already contains lots of options and its really huge, plus its hard to cover all cases. Operator config itself is very simple and only supports env variables.

 WDYT? Maybe there is another solution?

**Comment by tesharp** [comment]
I ended up using option 2 and creating all `VMServiceScrape` manually. Option 1 doesn't really work when deploying resources with gitops since the service monitor resources do not exist at the time of its deploying the `VMCluster` resource.
