### ISSUE TITLE
VMPodScrape support for authentication

### ISSUE THREAD

**Issue by DaspawnW** [VictoriaMetrics/operator#151]
Hi,

first of all, I'm testing this project now since 3 1/2 hours and its amazing... I was able to replace prometheus near to 90% for now :-)

While checking the VMPodScrape I detected that it seems not to be possible to define basicAuth for the requests, is this right?
Or do you maybe see a way to add such a parameter to the CRD?

Thank you in advance,
Best regards,
 Björn

**Comment by f41gh7** [comment]
Hello, thanks for reporting. 

   Its a bug, need to add missing auth params (basic and bearer). Will fix it soon.

**Comment by f41gh7** [comment]
Was added to v0.8.0 release.
