### ISSUE TITLE
vmalertmanager StatefulSet failed to create Pods due to missing ServiceAccount

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/operator#159]
Hello. I experienced a confusing issue.

### My environment

- kubernetes v1.19.7 on private cloud
- VictoriaMetrics operator v0.7.4

### An issue I experienced

At some point, when probably the API server is temporarily down, the ServiceAccount referenced by vmalertmanager StatefulSet disappeared before I knew it and the StatefulSet was unable to create Pods. The ServiceAccount is supposed to be automatically created by the operator, not created by the user (= me). Also, the StatefulSet was re-created. the VMAlertmanager CR has always existed.

Finally, I deleted the StatefulSet. Then, the operator re-created the StatefulSet and ServiceAccount immediately and the problem went away.

The points I'm confused about are:

- the ServiceAccount suddenly disappeared and the StatefulSet is re-created.
- the operator did not re-create the ServiceAccount although it did not exist.

### Other info

The VMAlertmanager resource is https://github.com/cybozu-go/neco-apps/blob/main/monitoring/base/victoriametrics/alertmanager.yaml

The operator's log (`kubectl logs`) is https://gist.github.com/morimoto-cybozu/8194b90a4b9234273f7fcd4140433fab

**Comment by f41gh7** [comment]
Hello, seems like, its an issue with controller-manager and it's garbage-collection mechanism. For some reason, it's not able to find owner of `vmalertmanager`'s serviceAccount and deleted it.

 Need to investigate it. Probably, additional watcher is needed.

**Comment by umezawatakeshi** [comment]
Thank you for your time.

**Comment by f41gh7** [comment]
Fix was included at master branch, now operator watches for owned resources (like serviceAccount) and must recreate it after deletion. 
 Another issue with cluster-wide objects were partially fixed - namespaced resources cannot own cluster one.  And operator shouldn't add owner reference for such objects. 
  But it brings one problem, such resources cannot be garbage collected, after operator will be deleted. Need to think, how to fix it better.

**Comment by ymmt2005** [comment]
> But it brings one problem, such resources cannot be garbage collected, after operator will be deleted. Need to think, how to fix it better.

We use finalizers for such cases.

**Comment by umezawatakeshi** [comment]
@f41gh7 I see.. It seems that re-creation behavior works fine. I appreciate your help.

**Comment by f41gh7** [comment]
> > But it brings one problem, such resources cannot be garbage collected, after operator will be deleted. Need to think, how to fix it better.
> 
> We use finalizers for such cases.

 Thanks, it looks interesting. Will use it as well.

**Comment by umezawatakeshi** [comment]
Hello. I expected a similar issue again in a similar situation.

### My environment

- operator 0.9.0

### An issue I experienced

During all-servers rolling reboot (i.e. api-servers, operators, and vmagents rebooted), vmagent Deployment could not start Pod due to missing account token.

- This time, ServiceAccount exists and `ownerReference` is correct. However, the Pod try to mount wrong account token secret (wrong name) and failed it.
- some of Deployment and ServiceAccount were re-created, in spite of VMAgent resource is not updated.
```
$ kubectl get deployment -n monitoring
NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
victoriametrics-operator      2/2     2            2           90d
vmagent-vmagent-largeset      3/3     3            3           3h25m
vmagent-vmagent-smallset      1/1     1            1           3h25m <- this timing
vmalert-vmalert-largeset      3/3     3            3           3h25m
vmalert-vmalert-smallset      1/1     1            1           33d
vminsert-vmcluster-largeset   3/3     3            3           14d
vmsingle-vmsingle-smallset    1/1     1            1           20d
$ kubectl get serviceaccount -n monitoring
NAME                                     SECRETS   AGE
victoriametrics-operator                 1         90d
vmagent-vmagent-largeset                 1         3h25m
vmagent-vmagent-smallset                 1         3h25m
vmalert-vmalert-largeset                 1         3h25m
vmalert-vmalert-smallset                 1         33d
vmalertmanager-vmalertmanager-largeset   1         9d
vmalertmanager-vmalertmanager-smallset   1         9d
vmcluster-vmcluster-largeset             1         14d
vmsingle-vmsingle-smallset               1         20d
```

I deleted the Pod. Re-created pod was able to mount correct account token secret and successfully started.

### Other info

`kubectl logs <vm-operator>` is [here](https://gist.github.com/umezawatakeshi/8416ef4aa7d662b2e9d0e012ff1f68e6)

**Comment by f41gh7** [comment]
Damn, thanks, will try to fix it soon.

**Comment by f41gh7** [comment]
I've added finalizers to every object created by operator.  I hope, it must solve this issue. Still cannot reproduce it with my setup (

**Comment by umezawatakeshi** [comment]
Thank you. I will try it.

**Comment by f41gh7** [comment]
Hope its ok. Feel free to re-open or create new issue, if it happen again.
