### ISSUE TITLE
vmalert minor feedback

### ISSUE THREAD

**Issue by afoninsky** [VictoriaMetrics/operator#160]
1. `.topologySpreadConstraints` key in VMAlert crd is ignored (haven't checked others) -> resulting pods don't have this key, rule is not applied when condition is met
2. VMAlert should have `.externalLabel` (as VMAgent) as vmalert supports it
3. `.topologySpreadConstraints.maxSkew` and `.topologySpreadConstraints.whenUnsatisfiable` are optional in API but required in current crd spec
4. (optional) currently we specify alertmanager config only as a string (`.configRawYaml`, secret), it would be cool if we can specify it as yaml -> more options for templating

**Comment by f41gh7** [comment]
1. seems to be work as expected.
2. Added at master branch.
3. https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#topologyspreadconstraint-v1-core according to this doc maxSkew and whenUnsatisfiable are required fields.
4. seems to be not possible with kubernetes crd generation tool - it doesn't allow unstructured data types.

**Comment by f41gh7** [comment]
Work for alertmanager configuration enhancement continue at this issue https://github.com/VictoriaMetrics/operator/issues/188
