### ISSUE TITLE
Dynamic volume resize for VMSingle/VMCluster without pods restart

### ISSUE THREAD

**Issue by vpedosyuk** [VictoriaMetrics/operator#161]
We use Helm charts to deploy VM, sometimes we need to increase storage size. For example, this includes cases when:
* the VM load always grows instead of being constant
* there's a need to change the retention period for the existing cluster
* there's a need to add some spare storage for background merges

With Helm we can't just increase PVC template size for vmstorages because of statefulset constraints in k8s. In order to increase our disks, we either add another replica pod of vmstorage or manually edit resizable PVC in GKE, which is very inconvenient for many reasons.

Some database operators have solved the issue: as I understood their operator patches PVC, then deletes the statefulset with `--cascade=false` so that pods remain untouched, and then creates the statefulset with renewed storage requests so that new replicas get created with new storage size.

A few examples:
https://github.com/elastic/cloud-on-k8s/pull/3752
https://github.com/zalando/postgres-operator/pull/958

P.S. Further improvements could be, for example, a kind of watcher that automatically adjusts PVCs depending on the "free storage threshold" that a user specifies for VMSingle/VMCluster.

**Comment by f41gh7** [comment]
Hello, it looks really interesting, need to implement it, thanks for suggestion.

**Comment by f41gh7** [comment]
Will be included to the next release.

**Comment by f41gh7** [comment]
Included to 0.12.0 release
