### ISSUE TITLE
VMAlertManager StatefulSet was deleted when k8s control planes down

### ISSUE THREAD

**Issue by masa213f** [VictoriaMetrics/operator#164]
Hello.
I experienced a strange behavior of the VictoriaMetrics operator.
Please let me know if you know anything about it.

### Environment
- Kubernetes v1.19.7
- VictoriaMetrics operator v0.7.4

### An issue I experienced

- I rebooted the machines which k8s control planes (kube-apiserver etc.) run on.
- Then a StatefulSet generated by a VMAlertmanager was deleted and the MV operator re-created it.

### Other info

I checked the source of the VM operator, but I cannot find any logic to remove the StatefulSet.
And I don't see any setting errors.

### Log
```
{"level":"info","ts":1613614128.1669858,"logger":"controllers.VMAlertmanager","msg":"Reconciling","vmalertmanager":"monitoring/vmalertmanager"}
{"level":"info","ts":1613614128.1908672,"logger":"factory","msg":"Creating a new sts","reconcile.VMAlertManager.sts":"vmalertmanager","ns":"monitoring","sts.Namespace":"monitoring","sts.Name":"vmalertmanager-vmalertmanager"}
{"level":"info","ts":1613614128.1990695,"logger":"factory","msg":"new sts was created for alertmanager","reconcile.VMAlertManager.sts":"vmalertmanager","ns":"monitoring"}
{"level":"info","ts":1613614128.1990888,"logger":"factory","msg":"updating vmalertmanager sts"}
```
[vmoperator.log](https://github.com/VictoriaMetrics/operator/files/6008356/vmoperator.log)

**Comment by f41gh7** [comment]
Hello, thanks for reporting, seems like its the same problem with https://github.com/VictoriaMetrics/operator/issues/159

 Will investigate and fix it.
