### ISSUE TITLE
Untighten format validation of image version

### ISSUE THREAD

**Issue by morimoto-cybozu** [VictoriaMetrics/operator#178]
The version of the Alertmanager is configurable via `.spec.image.tag` in `VMAlertmanager`.
The controller parses this version to handle the command-line options of the Alertmanager according to its version.
Unfortunately for me, the version parser requires the version should comply with Semantic Versioning and rejects slightly modified versions like "0.21.0.2."
It would be convenient if the parser could accept such versions.

FYI
I add the fourth number to the version of the Alertmanager in order to distinguish container images with different configurations.
The first image I built for Alertmanager 0.21.0 is named "0.21.0.1."
The second image built with a modified Dockerfile is named "0.21.0.2."

**Comment by f41gh7** [comment]
will be included into next release.
