### ISSUE TITLE
Feature request: VMAlertmanager config via custom resource

### ISSUE THREAD

**Issue by ve4eslav** [VictoriaMetrics/operator#188]
According to [quick-start.MD](https://github.com/VictoriaMetrics/operator/blob/master/docs/) the only way to add config into VMAlertmanager is Secret, containing all routes,receivers and inhibit-rules.

It will be better to maintain configs via custom resource like VMAlertmanagerConfig that will contain at least connected routes and receivers. It would also be nice to have flag "continue: boolean"

**Comment by f41gh7** [comment]
Need to look at it. In general, i dont like it much - CRD object depends on another CRD object.
 
 Probably, its possible to embed this configuration into `VMAlertmanager` spec.

**Comment by f41gh7** [comment]
New `CRD` was added to the master branch and will be included into the next release https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmalertmanagerconfig

 Note, its compatible with Alertmanager version `v0.22.+` and uses a bit different case for field names ( snake case) like alertmanager config. So its not compatible with `prometheus-operator` CRD. Probably, it will be possible to implement some converter in the future releases.

 Also, it uses modern alertmanager config options (lime mute_time_intervals and etc).

https://prometheus.io/docs/alerting/latest/configuration/

**Comment by f41gh7** [comment]
added to the `v0.18.0` release.

 Feel free to open new issue, if you find some bugs at `VMAlertmanagerConfig`

**Comment by r0fls** [comment]
As far as I can tell this was a breaking change: does the new spec no longer support additional files being created on the Alertmanager pod? The method before (using a secret) was loading a second alert formatting template file onto the pod, which doesn't seem to be supported with the new CRD spec here: https://docs.victoriametrics.com/operator/api.html#vmalertmanagerconfigspec

Am I missing something, or would a PR to update this spec to support additional files on the resulting alertmanager pod be accepted?
