### ISSUE TITLE
[vm-single] default port

### ISSUE THREAD

**Issue by misterkramer** [VictoriaMetrics/operator#220]
Hi! 
Why `VM_VMSINGLEDEFAULT_PORT=8429` instead `8428`? Port `8429` belongs to the vmagent.

https://github.com/VictoriaMetrics/operator/blob/master/vars.MD

**Comment by f41gh7** [comment]
Hello, it's legacy behavior. `VMSingle` listens for `8429` port.

 For now, its too late to make such change, because it may break users configuration.

 Its possible to schedule for v1.0 release.

**Comment by misterkramer** [comment]
Ok, thanks for the info!
