### ISSUE TITLE
different number of targets after each vmagent restart in the OpenShift 

### ISSUE THREAD

**Issue by fatowl-github** [VictoriaMetrics/operator#235]
Hello
We are testing vmagent as the substitution for OpenShift platform Prometheus running agent in the openshift-monitoring namespace.  All targets for vmagent providing vmagent-operator , as we expect. But we have some uncertainty, indeed... Sometimes, started vmagent pod feels 125 targets ( it's looks pretty well , like full cluster monitoring coverage by.) But after restarting the vmagent number of targets unpredictable changing. From one start to the other it would be or 110, or maybe 45. What could be the reason for this behavior?

Thank you  very much!

**Comment by f41gh7** [comment]
Hello, which version of vmagent do you use? probably, its related to this issue: 
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1240

  When some service wasn't properly update for corresponding endpoints.

**Comment by sergsmirnoff** [comment]
Hello,

vmagent coming from victoriametrics-operator.v0.14.1

**Comment by sergsmirnoff** [comment]
Is vmagent from victoriametrics-operator v0.14.1 affected by https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1240 ?

**Comment by f41gh7** [comment]
Yep, its v1.58.0 by default. Can you try version of vmagent from master branch? Does it solve an issue?
 
 You can build it with 
```bash
git clone git@github.com:VictoriaMetrics/VictoriaMetrics.git
make package-vmagent
```
 It will produce docker image.

**Comment by f41gh7** [comment]
related issue was fixed at vmagent.
