### ISSUE TITLE
Add default values for keys to crd

### ISSUE THREAD

**Issue by stress-t** [VictoriaMetrics/operator#236]
Please add values for keys to crd
VictoriaMetrics is evolving rapidly and key values change very quickly. The CRD itself is very large and it is quite difficult to determine the current default value

**Comment by f41gh7** [comment]
Hello.

  Can you clarify a bit, with some example for instance, which values needs proper default values? 
 
 I hope, many validation issues must be solved after this issue will be finished https://github.com/VictoriaMetrics/operator/issues/28

**Comment by stress-t** [comment]
Example: I created a new yaml file with the kind VMAgent. When can I see which vmagent path in docker hub is being used (this is only in code for now)

**Comment by f41gh7** [comment]
Ahh, all default values can be found there https://github.com/VictoriaMetrics/operator/blob/master/vars.MD

 It can be changed with corresponding env variables.

**Comment by stress-t** [comment]
How can i guess that VM_VMAGENTDEFAULT_IMAGE is used in image -> repository
The CRD specification already has a "Default" field.
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility

It doesn't use env variables. it using CRD specification
```
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  replicaCount: 1
  image:
    repository: xxxx/victoriametrics/vmagent
```

**Comment by f41gh7** [comment]
Well, default value for CRD spec is not supported well, as far as i see, its GA since 1.17 version. And doc recommends to use admission webhook for default values. Need to check, is it possible to generate it with controller-gen or not. 

 What do you think about documentation improvements? Could it solve such kind of issues?

**Comment by stress-t** [comment]
yes in the documentation

**Comment by f41gh7** [comment]
Update readme with operator config section.
