### ISSUE TITLE
Feature Request: Suppress the generation of a default alertmanager configuration

### ISSUE THREAD

**Issue by zoetrope** [VictoriaMetrics/operator#244]
I am using [bitnami-labs/sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) to generate a secret resource for alertmanager configuration.

However, VictoriaMetrics-operator seems to generate a default secret automatically when it does not exist, as below,.
https://github.com/VictoriaMetrics/operator/blob/40e9317512856286d9a2ceee96da74b93f56c9ff/controllers/factory/alertmanager.go#L565

It is undesirable to me that VictoriaMetrics-operator generates the secret before sealed-secrets.
Is there any way to suppress this generation?

**Comment by f41gh7** [comment]
Hello, agreed, this logic must be changed. It was done for early versions.

 Need to change it for `if configSecret is defined, do nothing`.

**Comment by f41gh7** [comment]
Fix will be included into next operator release, for now it can be tested with master branch.

**Comment by f41gh7** [comment]
Changes was included to the `0.15.0` release. Sorry for delay.
