### ISSUE TITLE
Some questions about operators

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/operator#258]
1、Vmsingle is similar to Prometheus local storage?

2、vmservicescrape_ service_ Sd.yaml file has an error: regex: true

3、Is Kube state metrics required for k8s cluster deployment?

4、Does k8s cluster deployment need to install metrics server?

5、Does vmagent have a dashboard similar to Prometheus

**Comment by f41gh7** [comment]
1. Yep, it almost the same, but it cannot scrape metrics or execute alerts (vmagent and vmalert is needed).

2.  Thanks! sorry for that, documentation is not good and there can be some typos and mistake. Any kind of help is welcome.

3. kube-state metrics can be installed separately. There is also `all-in-one chart`, that install everything needed to monitor k8s cluster from scratch https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack

4. metrics server can be also installed separately, there is no such requirement for operator.

5. neither vmagent, nor vmsingle, doesn't have built-in dashboard. We are working on it and some of next VictoriaMetrics releases will include ui for `vmselect` of `VMCluster` and `VMSingle`

**Comment by ktpktr0** [comment]
Thank you for your reply. Now it seems that the operator is more like https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack But the collection of related components is not as comprehensive as chart warehouse. The installation mode of helm is more like the implementation of Kube Prometheus. Victoria metrics should be released for a long time, but I seldom use it in production environment through search engine. Therefore, I am looking forward to the performance test of Kube Prometheus and victoria-metrics-k8s-stack to learn that Victoria metrics can replace Prometheus.
