### ISSUE TITLE
Support for prometheus-config-reloader 0.43+

### ISSUE THREAD

**Issue by morimoto-cybozu** [VictoriaMetrics/operator#259]
prometheus-config-reloader replaced the `--rules-dir` flag with the `--watched-dir` flag in 0.43.0. 
https://github.com/prometheus-operator/prometheus-operator/pull/3457/commits/dcf34c55bc7596fe9135b6a37344c7578586c80d
VM operator uses a hard-coded flag name of `--rules-dir` even when prometheus-config-reloader 0.43.0+ is specified via `VM_VMAGENTDEFAULT_CONFIGRELOADIMAGE`.  The resulting Pod fails to start.

We need to switch the flag name by detecting the reloader version automatically, or if it is difficult, by accepting some additional environment variable for the flag name.  I suppose that autodetection cannot work well because the image tag does not always represent the reloader version.

If using prometheus-config-reloader 0.42 or older is mandatory, it would be good to document that requirement clearly.

**Comment by f41gh7** [comment]
Thanks for reporting.  For now, i think that its ok to parse version of config-reloader image on best-effort and apply proper flag args.

 Later i want to replace prometheus-config-reloader with own implementation, its needed to solve this issue https://github.com/VictoriaMetrics/operator/issues/124

**Comment by f41gh7** [comment]
Changes was included to the `0.15.0` release, default version of config-reloader image was updated.
