### ISSUE TITLE
When Create VMAlertmanager，makeStatefulSetSpec func joint one more "."

### ISSUE THREAD

**Issue by linkbug** [VictoriaMetrics/operator#268]
like this : 
Failed to resolve **### vmalertmanager-example-alertmanager-1.vmalertmanager-example-alertmanager.opcs.svc.cluster.local**.****:9094: lookup vmalertmanager-example-alertmanager-1.vmalertmanager-example-alertmanager.opcs.svc.cluster.local. on 192.115.0.14:53: no such host
code is  :
clusterPeerDomain = fmt.Sprintf("%s.%s.svc.%s.", cr.PrefixedName(), cr.Namespace, c.ClusterDomainName)

**Comment by f41gh7** [comment]
Thanks for reporting!

**Comment by f41gh7** [comment]
It shouldn't be an issue, its valid dns name. I suppose, that your kubernetes has different dns-domain.

 You can check it but executing following command inside any pod:
```bash
cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:5
```
 `cluster.local` is default dns domain for cluster. If you have other domain, change it with env variable added to the operator deployment:
```
env:
- name: VM_CLUSTERDOMAINNAME
  value: your-cluster-dns-domain
```

**Comment by linkbug** [comment]
use defalut ClusterDomainName
error log is "Failed to resolve ### vmalertmanager-example-alertmanager-1.vmalertmanager-example-alertmanager.opcs.svc.cluster.local.****:9094: lookup vmalertmanager-example-alertmanager-1.vmalertmanager-example-alertmanager.opcs.svc.cluster.local. "

"vmalertmanager-example-alertmanager-1.vmalertmanager-example-alertmanager.opcs.svc.cluster.local**.**" end with "**.**"

**Comment by Amper** [comment]
Hi @linkbug.
Is that question still relevant to you?

**Comment by Amper** [comment]
Closed due to lack of activity
