### ISSUE TITLE
operator's requests/limits too low

### ISSUE THREAD

**Issue by hamelg** [VictoriaMetrics/operator#282]
victoriametrics operator restarts often with the reason OOMKilled. The current values are 

```
    Limits:
      cpu:     120m
      memory:  320Mi
    Requests:
      cpu:     80m
      memory:  120Mi
```

Our operator is deployed by OLM in a openshift cluster 4.7. We can modify the default values in the CRD clusterserviceversions, but environment variables defined in the CRD subscriptions would be more appropriate.

**Comment by f41gh7** [comment]
May i ask you for some example with env variable, how to set it with openshift cluster? Or docs links.

**Comment by hamelg** [comment]
we use the CRD subscription to configure victoriametric operator with variables as described [here](https://github.com/VictoriaMetrics/operator/blob/master/vars.MD). I was thinking to use the same method, but I realized it is not possible : the operator can't change itself its limits/requests. At every operator upgrade we will have to modify the resource clusterserviceversion.spec.install.spec.deployments.spec.template.spec.containers.resources.... 

With openshift before 4.7, OLM ignores the resources defined in the spec.containers template. Maybe you could increase slightly the default memory limit at 500Mi to avoid OOMs.

**Comment by f41gh7** [comment]
Additional issue with high memory consumption problem https://github.com/VictoriaMetrics/operator/issues/285

 I hope, that after it will be fixed, memory consumption must be acceptable for given limits.

 Also, memory limit will be increased to 500Mi at the next release.

**Comment by f41gh7** [comment]
Added to the 0.17.1 release.

 Memory usage must be lower with this release.
