### ISSUE TITLE
Operator got OOMKilled

### ISSUE THREAD

**Issue by zensu** [VictoriaMetrics/operator#285]
Hello!

I have big openshift cluster (4.6) with deployed vmcluster (with hpa) + vmagent + vmalert. I use hpa in vmcluster in vminsert block. So I wanted to try use hpa to my vmselect and upgraded operator to more actual version. And I faced with OOMKilled problem. 
My previous version of operator was v0.14.2 and without pod OOMKilled. It had 5Gi maximum of limits and works perfectly.
After update to v0.15.0 (also v0.15.1, v0.15.1, v0.16.0) I got OOMKilled and raise up limits from 5Gi to 9Gi and it don't solve problem. 
I can't just indefinitely raise up limits for operator.

[operator's container_memory_working_set_bytes diff](https://user-images.githubusercontent.com/14234031/126081978-b0c9dcdf-c4c1-45b1-8d3e-ea5092af6053.PNG)

**Comment by f41gh7** [comment]
Hello, its unexpected. May i ask  you  to collect memory profile, its possible since 0.16.0 version. 

steps:
1) port-forward for operator container
2) execute locally: 

```
curl http://localhost:8435/debug/pprof/heap > operator_mem_pprof
```

**Comment by f41gh7** [comment]
This profile can be attached here or sent to nik@victoriametrics.com.

**Comment by zensu** [comment]
pprof was sent to your email

**Comment by f41gh7** [comment]
Thanks, get it. Seems like its caused by kubernetes lib version update, listing secrets is too expensive. Going to fix it soon.

**Comment by f41gh7** [comment]
Can you try following docker image: `victoriametrics/operator:changes-secrets-list` from branch https://github.com/VictoriaMetrics/operator/tree/changes-secrets-list

 It must reduce memory usage.

**Comment by zensu** [comment]
> Can you try following docker image: `victoriametrics/operator:changes-secrets-list` from branch https://github.com/VictoriaMetrics/operator/tree/changes-secrets-list
> 
> It must reduce memory usage.

Thank you,
I builded image from that branch. It seems likes reduces memory a little, but it still a lot.
I was sent to you another pprof

**Comment by f41gh7** [comment]
> > Can you try following docker image: `victoriametrics/operator:changes-secrets-list` from branch https://github.com/VictoriaMetrics/operator/tree/changes-secrets-list
> > It must reduce memory usage.
> 
> Thank you,
> I builded image from that branch. It seems like reduces memory a little, but it still a lot.
> I was sent to you another pprof

 It helps a lot, thanks.  I've found few more places, that causes extra memory consumption. New commits pushed to the branch `https://github.com/VictoriaMetrics/operator/tree/changes-secrets-list`

  Can you test it and share memory profile, if problem persist?

**Comment by zensu** [comment]
Pulled new commits and build. Now it's pretty good, thank you. Memory consumption has decreased by half. 
Its good to me. Also I was sent new pprof if you would like to see current consumption.

**Comment by f41gh7** [comment]
> Pulled new commits and build. Now it's pretty good, thank you. Memory consumption has decreased by half.
> Its good to me. Also I was sent new pprof if you would like to see current consumption.

Great! What is current memory consumption?

   Yes, for sure, share profile, probably, its possible to optimization something else.

**Comment by zensu** [comment]
> Great! What is current memory consumption?
> 

Now it's about 4Gb. Less than before on v0.14.2 version.
Current pprof already was sent

**Comment by f41gh7** [comment]
@zensu  , i've added few more changes, it must also reduce memory usage. Can you pull it and try?

**Comment by f41gh7** [comment]
Added to the 0.17.1 release. Feel free to reopen if problem persists.
