### ISSUE TITLE
When "cr.Spec.Image.Tag" is empty use "c.VMAgentDefault.Version" as default in func "newDeployForVMAlert"

### ISSUE THREAD

**Issue by linkbug** [VictoriaMetrics/operator#287]
When "cr.Spec.Image.Tag" is empty use "c.VMAgentDefault.Version" as default in func "newDeployForVMAlert":

![image](https://user-images.githubusercontent.com/6823659/126456338-9069ed31-2d50-46da-ab33-0f07afc1ba28.png)

Should use **c.VMAlertDefault.Version** as default

**Comment by f41gh7** [comment]
Thanks for reporting! Will be fixed at the next release.

**Comment by f41gh7** [comment]
Added to the 0.17.1 release
