### ISSUE TITLE
HPA in VMCluster CRD

### ISSUE THREAD

**Issue by zensu** [VictoriaMetrics/operator#296]
Hello.
I added hpa block to my VMCluster to block vminsert, vmselect. It's work good.
But when I want to delete these HPA I go to VMCluster CRD and remove hpa blocks. So I faced with situation when block in CRD was removed but HPA resources not deleted.
Could you reproduce this behavior?
operator version v0.16.0

**Comment by f41gh7** [comment]
Hello, thanks for reporting. Its a bug, need to fix it.

**Comment by f41gh7** [comment]
Must be fixed at 0.17.2 version
