### ISSUE TITLE
VMPodScrape LabelSelector shouldn't be required

### ISSUE THREAD

**Issue by FRosner** [VictoriaMetrics/operator#307]
The field `selector` in the [`VMPodScrapeSpec`](https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmpodscrapespec) is  marked required. It will get translated to a respective action. However, if you are using annotations rather than labels, you still need to provide a label selector. I ended up providing a tautology in order to circumvent the fact that the label selector is required.

I am not sure what the reason behind the label selector being required is but I think it would be more flexible if you could leave it blank and just rely on custom actions for selection.

WDYT?

**Comment by f41gh7** [comment]
Makes sense for, since the next release it will be optional.

**Comment by f41gh7** [comment]
added to the `v0.18.0` release.
