### ISSUE TITLE
ServiceAccount "monitoring-system"

### ISSUE THREAD

**Issue by patstrom** [VictoriaMetrics/operator#323]
[`psp.yaml`](https://github.com/VictoriaMetrics/operator/blob/master/config/rbac/psp.yaml#L49) refers to a ServiceAccount called monitoring-system, but I cannot find where this SA is declared. Have I missed something? Or should it be ServiceAccount `vm-operator`?

**Comment by f41gh7** [comment]
Added to the v0.19.0 release. Feel free to re-open if it doesnt solve an issue
