### ISSUE TITLE
 Add flag to switch off VMConverterController

### ISSUE THREAD

**Issue by fatsheep9146** [VictoriaMetrics/operator#351]
https://github.com/VictoriaMetrics/operator/blob/0518cfa0af6845695372504f46e288de777d558b/internal/manager/manager.go#L252-L264

for VMConverterController, can we add a flag to switch on/off this feature? In our case, the prometheus-operator and vm operater both exists, but we make some changes for prometheus-operator‘s CRD for our own purpose, which will result in the error of  VMConverterController.

**Comment by f41gh7** [comment]
Its should be possible with env vars
```
#disable convertion for each object
VM_ENABLEDPROMETHEUSCONVERTER_PODMONITOR=false
VM_ENABLEDPROMETHEUSCONVERTER_SERVICESCRAPE=false
VM_ENABLEDPROMETHEUSCONVERTER_PROMETHEUSRULE=false
VM_ENABLEDPROMETHEUSCONVERTER_PROBE=false
```
https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#migration-from-prometheus-operator-objects

Does it help?
