### ISSUE TITLE
Documentation is incomplete, EmbeddedIngress doesn't list all fields

### ISSUE THREAD

**Issue by flokli** [VictoriaMetrics/operator#358]
I'd like to use VMAuth to expose some of victoria metrics outside the cluster.

I created VMAuth and VMUser according to the quick start.

The Ingress gets created.

However, for cert-manager to create a certificate, I'd also need to add a `cert-manager.io/cluster-issuer=…` annotation (and in general, I might want to add other annotations as well).

Could `EmbeddedIngress` get an annotations field, so setting arbitrary annotations becomes possible?

**Comment by flokli** [comment]
Indeed - a `kubectl explain vmauth.spec.ingress` does list that endpoint.

Could we switch to something like https://github.com/ahmetb/gen-crd-api-reference-docs instead?

It's being used to render the cert-manager and knative API reference docs, so should probably support everything we need.

**Comment by Amper** [comment]
I see that doc generation is no longer a problem now. I am closing the issue as irrelevant.
