### ISSUE TITLE
How to create vmagent cluster by Vmagent CR

### ISSUE THREAD

**Issue by arctan90** [VictoriaMetrics/operator#368]
By vmagent [doc](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets) 's suggestion, adding extraArgs promscrape.cluster.membersCount and  promscrape.cluster.memberNum will help to create a vmagent.
And then, how could I create a vmagent by VMAgent CR ? 
Does the 'shardCount' key  in crd work for this?

**Comment by f41gh7** [comment]
Hello,  yes, `shardCount` defines sharding for vmagent. It produces multiple vmagent deployments according to shard count.

 There is HA section at the docs [link](https://github.com/VictoriaMetrics/operator/blob/master/docs/high-availability.MD#vmagent)

**Comment by arctan90** [comment]
> Hello, yes, `shardCount` defines sharding for vmagent. It produces multiple vmagent deployments according to shard count.
> 
> There is HA section at the docs [link](https://github.com/VictoriaMetrics/operator/blob/master/docs/high-availability.MD#vmagent)

Thank you for this info. It works.
