### ISSUE TITLE
The statefulsets produced by the operator couldn't be conveniently restarted using `kubectl rollout restart`

### ISSUE THREAD

**Issue by g7r** [VictoriaMetrics/operator#389]
The problem is that the statefulsets produced by the operator have `updateStrategy.type: OnDelete` which effectively prevents rollout restart from working. It requires manual work and manual coordination when someone needs to restart the statefulset produced by the operator.
1. The one who wants to restart the statefulset could be a generic person making maintenance of Kubernetes cluster and not being aware of VictoriaMetrics operator internals.
2. It is error prone to manually coordinate restart of such statefulset by `kubectl delete pod` when there are a lot of pods into it.

I suggest that `updateStrategy.type` should be `RollingUpdate` and the logic performing updates by deleting pods should be removed from the operator.

**Comment by f41gh7** [comment]
I think, it's the price, which should be payed for proper rolling update and statefulset management. 

 The main issue with kubernetes rolling update, it requires manual intervention and it cannot be canceled. 
 For instance:
1) you made some mistake with container image
2) pod stack in crash loop back-off. 
3) you fixed version for correct one with kubectl apply.
4) nothing happen with old pod, there is no error at logs. You have to manually delete it.

 That's why onDelete policy is used.

 For your restart case, just change some label at podMetadata.labels with kubectl patch, it must trigger statefulset restart. Something like:

```
kubectl patch vmalertmanager example --patch '{"spec": {"podMetadata": {"labels": {"restarted_at": "some-tid"}}}}'
```

**Comment by g7r** [comment]
I see. But I'm still not convinced. It is a pretty standard story for Kubernetes maintenance engineer that in the case of stuck statefulset pod it should be manually deleted. VictoriaMetrics operator provides a workaround for it but at the cost of complication of usual maintenance operations on statefulsets. I haven't yet seen a pod crashloop on VictoriaMetrics' statefulsets but I've already made a lot of manual restarts. These restarts don't obey the rules of rollout. One can restart all statefulset pods simultaneously.

I think it is wrong to "fix" statefulset controller logic inside VictoriaMetrics operator. It is against abstraction boundaries and it increases WTF metric for Kubernetes maintenance engineers.

**Comment by f41gh7** [comment]
Sorry for delay.

 Well, main purpose of operators - simplify application management process. I don't think, that manual rolling update feature abuses statefulset controller logic. OnDelete strategy is special mode, where kubernetes delegates update process to end user or application.

  But this behavior must be optional, so i think strategy for statefulsets must be configurable. If onDelete is set for vmstorage/vmselect/vmalertmanager, operator manages updates and rollout, which is default behavior. With rollingUpdate strategy it does nothing and relies on kubernetes statefulset controller. 

 Hope it should solve an issue for you.

**Comment by g7r** [comment]
It likely should, thanks!

**Comment by f41gh7** [comment]
added to the 0.22.0 release. Feel free to re-open if it doesn't help
