### ISSUE TITLE
VMAlertmanagerConfig: Is it possible to add an option to control namespace label ingestion into to matchers block?

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/operator#390]
Hey guys, 

You probably saw ([here](https://github.com/prometheus-operator/prometheus-operator/discussions/3733) or [here](https://github.com/prometheus-operator/prometheus-operator/issues/3737)) the discussion around adding `namespace` label into each parent route `matchers` after merging [VMAlertmanagerConfig](https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmalertmanagerconfig). 
I faced the same situation recently when we decided to migrate to Victori-Metrics on k8s and take care of deploying/controlling alerts by `victoria-metrics-operator`, but as we have many alerts without `namespace` label and a lot of them rely on our `Global-View` ([promxy](https://github.com/jacksontj/promxy) wich merge metrics from all clusters into one) it won't work for us to have `namespace` label inserted into each `matchers` block.

Why are your thoughts? Can we add some flag to disable such behavior?

**Comment by f41gh7** [comment]
Hello, sry for delay. I think, that it's possible to make this behavior optional and do not add namespace matcher by default.

 Open question for me, should it be defined at VMAlertmanagerConfig at at VMAlertmanager itself? 

 It looks like, it's better to have such option at VMAlertmanager from security point of view.

**Comment by b2ronn** [comment]
made a temporary solution , in controllers/factory/alertmanager/config.go 
`		subRoutes = append(subRoutes, buildRoute(amcKey, amcKey.Spec.Route, true))
`
change to
`		subRoutes = append(subRoutes, buildRoute(amcKey, amcKey.Spec.Route, false))
`
built, pushed to the internal registry, changed the path to the image in the crd and waiting for a normal solution .

**Comment by Vladikamira** [comment]
> Open question for me, should it be defined at VMAlertmanagerConfig at at VMAlertmanager itself?
> It looks like, it's better to have such option at VMAlertmanager from security point of view.

For me as well, you can take a look to an attempt to implement such option [here](https://github.com/prometheus-operator/prometheus-operator/pull/3821)

Also, I understand the logic behind injecting `namespace` label into matcher, as it's kind of way to protect from overlapping on previous matchers, so we should inform people that they have to control route overlapping by them self

**Comment by f41gh7** [comment]
Option `disableNamespaceMatcher: false` was added to the master branch.

It can be defined for alertmanager, by default it's disabled.

 Example:
```yaml
kind: VMAlertmanager
spec:
  disableNamespaceMatcher: true
```

  In this case matcher with namespace won't be added to the alertmanager configuration.

**Comment by f41gh7** [comment]
added to the 0.22.0 release. Feel free to re-open if it doesn't help
