### ISSUE TITLE
A wrong configuration in example doc 

### ISSUE THREAD

**Issue by arctan90** [VictoriaMetrics/operator#391]
In  https://github.com/VictoriaMetrics/operator/blob/master/docs/high-availability.MD , the VMAgent CR.
vmAgentExternalLabelName: vmagent-ha will cause alertmanager issue an error message 'response body: "invalid label set: invalid name \"vmagent-ha\""'

It was said that  '-' is not allowed in label name. So in this example, vmAgentExternalLabelName: vmagent-ha should be changed to something like vmAgentExternalLabelName: vmagentHa

**Comment by f41gh7** [comment]
Thanks for pointing will be fixed!

**Comment by f41gh7** [comment]
Fixed at master branch
