### ISSUE TITLE
Failed to build with go 1.17

### ISSUE THREAD

**Issue by masa213f** [VictoriaMetrics/operator#392]
Hi,

I tried to build v0.21.0 with go 1.17, but I cannot.

```
$ go version
go version go1.17.3 linux/amd64
$ CGO_ENABLED=0 go build -trimpath -o bin/manager main.go
go: updates to go.mod needed; to update it:
        go mod tidy
```

It may need to `go mod tidy`. Could you update the `go.mod`?

**Comment by f41gh7** [comment]
Can you try it  from master branch now? I've updated deps and changed go version for 1.17

**Comment by f41gh7** [comment]
fixed at master branch
