### ISSUE TITLE
Question: how to install vmoperator/vmagent on kubernetes cluster?

### ISSUE THREAD

**Issue by myhellone** [VictoriaMetrics/operator#410]
Hi, 

I have Victoria metrics cluster on virtual machines and i want to collects metric from kubernetes cluster (installed on another vm). 
If I am good at it, I need an vmagent installed on kubernetes cluster, (but I don't need a whole victoriacluster on kubernetes). 

what is minimal configuration form motioning kubernetes clustetr (and some ex. node_exporters)?
is there any documentation for a case like mine?

**Comment by denisgolius** [comment]
Hi @myhellone !
See https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-cluster.html#3-install-vmagent-from-the-helm-chart it might help.

**Comment by myhellone** [comment]
ok ;) so my monitoring stack  is based on argoCD, I have some issue but finaly I have installed vmoperator (argocd by helm) and them vmagent and connect it to external victoriametric, 
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metric
  namespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: victoria-metrics-operator
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
`
