### ISSUE TITLE
Wrong configMaps mount point for VMAlertmanager

### ISSUE THREAD

**Issue by Sammyant** [VictoriaMetrics/operator#413]
Hi, 
we appreciate your great work on the operator!
We noticed that the configmap specified in configMaps field is mounted into /etc/vm/configs/<configmap-name> instead of /etc/alertmanager/configmaps/<configmap-name>

we use 
VictoriaMetrics Operator 0.22.0 
Openshift 4.8.22

CR:
```
spec:
  configMaps:
    - alertmanager-config
```
Pod manifest:
```
volumeMounts:
  - name: configmap-alertmanager-config
     mountPath: /etc/vm/configs/alertmanager-config`
```
In the pod with alertmanager we can't find directory from manual and find strange cycle of links:

`can't cd to /etc/alertmanager/configmaps/alertmanager-config/: No such file or directory
`
ls /etc/vm/configs/alertmanager-config 
drwxr-sr-x    2 root     10017600        23 Jan 20 11:09 ..2022_01_20_11_09_11.210401171
lrwxrwxrwx    1 root     10017600        31 Jan 20 11:09 ..data -> ..2022_01_20_11_09_11.210401171
lrwxrwxrwx    1 root     10017600        16 Jan 20 11:09 test.tmpl -> ..data/test.tmpl

ls -la /etc/vm/configs/alertmanager-config /..2022_01_20_11_09_11.210401171
-rw-r--r--    1 root     10017600      8474 Jan 20 11:09 test.tmpl

**Comment by f41gh7** [comment]
It's desired behavior, can you add more context, in which case such error happens? Some default alertmanager templates or default openshift alertmanager configuration? 

 In case of VMAlertmanagerConfig, i think, that secret/configmaps pathes can be rewritten.

**Comment by Sammyant** [comment]
It's not an error it's just not clear for us. 
Why the configmap from the configMaps field doesn't mount to the /etc/alertmanager/configmaps/ directory, according to the documentation

> The ConfigMaps are mounted into **/etc/alertmanager/configmaps/**<configmap-name>

https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmalertmanagerspec

So, we added a simple configmap with an email template but didn't find a template file (test.tmpl) in the mentioned directory and it was the main cause why our vmAlertmanager instance didn't use the template 
(we set template path as /etc/alertmanager/configmaps/<configmap-name>/*.tmpl)

**Comment by Sammyant** [comment]
Thanks)
