### ISSUE TITLE
Operator Pod throws error after upgrading vm operator to the latest version

### ISSUE THREAD

**Issue by arunslalgit** [VictoriaMetrics/operator#428]
the upgrade was from version 0.3.1 to 0.7.1 of operator

Issue:
Operator pod went into CrashLoopBackoff status with below error:

{"level":"error","ts":1644850319.6091275,"logger":"setup","msg":"cannot setup manager","error":"cannot set kubernetes server version: cannot parse kubernetes server minor version: \"21+\" as uint: strconv.ParseUint: parsing \"21+\": invalid syntax","stacktrace":"main.main\n\t./main.go:43\nruntime.main\n\truntime/proc.go:255"}

Can you please check if it has something to do with this commit?

https://github.com/VictoriaMetrics/operator/commit/5a64f6c01d535f5500a9d9a81ac851f9f12d547a

**Comment by f41gh7** [comment]
Must be fixed at 0.23.3 version.
