### ISSUE TITLE
How to set search.maxStalenessInterval when run via VmOperator?

### ISSUE THREAD

**Issue by withnale** [VictoriaMetrics/operator#433]
I've done some testing within a docker compose environment and have determined that we need to set `search.maxStalenessInterval` to a specific value for our needs. However, I can't see any documentation about how I would set this variable when updating an already deployed vmoperator managed cluster.

Any pointers?

**Comment by f41gh7** [comment]
Each operator CR object has special fields - `extraArgs` and `extraEnvs`, where additional configuration for application can be placed.

  For your case, try to add it at `extraArgs`:

```
kind: VMSingle
spec:
   extraArgs:
     search.maxStalenessInterval: "1m"

**Comment by f41gh7** [comment]
Feel free to re-open, if this information doesn't help
