### ISSUE TITLE
use env vars for sensetive data instead of command line arguments.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#440]
currently, operator configures command line arguments with usernames, password and token. This is not secure and is not expected by user.

  Move it to the env variables, hide sensitive data at secret.

**Comment by tejavegesna** [comment]
May be do something like this

https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L1148

https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L434

**Comment by f41gh7** [comment]
Was added at the v0.30.0 release
