### ISSUE TITLE
operator doesn't remove finalizers from urlRelabelConfig

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#442]
1) Check at vmagent delete request.

2) Check other places, where it might happen.

3) Check for orphaned objects.

**Comment by hamelg** [comment]
There is the same issue with additionalScrapeConfigs. Finalizers on theses secrets are not removed when deleting the related vmagent.

**Comment by f41gh7** [comment]
Changes was included to the v0.24.0 release. Feel free to re-open the issue if it doesn't solve it.
