### ISSUE TITLE
All targets display in web UI when vmagent is in shard model 

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/operator#445]
When vmagent is in shard model, every shard only display a part of  all targets. If I want find a specific target in UI, I would have to flush the UI many times(because of round-robin load balance). There is a method to get all targets in one time open vmagent UI? Has the Community provided any reliable solutions? 
My environments:
In Kubernetes cluster, vmagent has 3 sharding, and visit vmagent UI from load balance to ingress and then to service.
Thanks!

**Comment by sreeragunnikrishnan** [comment]
This is a very much needed feature

**Comment by hagen1778** [comment]
This issue is related to vmagent, not operator - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4018
