### ISSUE TITLE
vm-operator pod failed to start due to error parsing Kubernetes version

### ISSUE THREAD

**Issue by lerakhoteenkova** [VictoriaMetrics/operator#449]
vm-operator pod cannot start because Kubernetes version is not type on int
here's log error message from pod
`"msg":"cannot setup manager","error":"cannot set kubernetes server version: cannot parse kubernetes server minor version: \"20+\" as uint: strconv.ParseUint: parsing \"20+\": invalid syntax","stacktrace":"main.main\n\t./main.go:43\nruntime.main\n\truntime/proc.go:255`

and this is output from `kubectl version` command
`erver Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.12-gke.1500", GitCommit:"d32c0db9a3ccd0ac73b0b3abd0532505217b376e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:02Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by f41gh7** [comment]
Hello, can you try to upgrade operator  to the `v.0.23.2`+ version? It contains needed fix.

**Comment by lerakhoteenkova** [comment]
worked for me thank you!
