### ISSUE TITLE
Missing finalizers in deploymentSpec?

### ISSUE THREAD

**Issue by lujiajing1126** [VictoriaMetrics/operator#451]
I suppose there should be a `finalizers` field in the deployment,

https://github.com/VictoriaMetrics/operator/blob/10a53e58c8dcb388e7dda62db836513fb0618e90/controllers/factory/vmsingle.go#L128-L148

Otherwise, we have to wait for another round of reconciliation.

If so, I could send a PR.

**Comment by f41gh7** [comment]
Well, in theory yes, it's good place for finalizer. In practice it doesn't matter, next reconciliation loop triggers immediately. 

 I think, it's better to place finalizer at deployment spec, as you mentioned, and revise logic for other deployments.

**Comment by lujiajing1126** [comment]
> Well, in theory yes, it's good place for finalizer. In practice it doesn't matter, next reconciliation loop triggers immediately.

What do you mean by "next reconciliation loop triggers immediately", as I understood, after the deployment creation, the reconciliation loop will not be invoke until someone modifies the CRD again.
