### ISSUE TITLE
Can't customize VMServiceScrape of vmcluster

### ISSUE THREAD

**Issue by artifactori** [VictoriaMetrics/operator#454]
I can't customize the `VMServiceScrape` of `VMCluster` to add extra labels on the metrics.

I've checked the [API docs](https://docs.victoriametrics.com/operator/api.html#vmclusterspec) and [the `VMServiceScrape` creation code from `VMCluster`](https://github.com/VictoriaMetrics/operator/blob/06dada488d629d4d321985e80d14ee04e099bdfd/controllers/factory/scrapes.go#L772-L821) and seems there's no way to modify it for now.

**Comment by f41gh7** [comment]
Changes was included to the v0.24.0 release. Feel free to re-open the issue if it doesn't solve it.

 Thanks for contribution!

**Comment by artifactori** [comment]
It does solve the problem, so I don't need to reopen the issue. Thank you very much, @f41gh7!
