### ISSUE TITLE
allow set terminationGracePeriodSeconds for cluster (or all) components

### ISSUE THREAD

**Issue by frank-berlin** [VictoriaMetrics/operator#460]
In a high load environment like bigger k8s cluster > 1k nodes and a lot of pod churn the default terminationGracePeriodSeconds (30s) is not sufficient for a graceful restart of for example vmselect, vminsert,...
It would be helpful to allow terminationGracePeriodSeconds to change via the CRD.

**Comment by f41gh7** [comment]
Changes was included to the v0.24.0 release. Feel free to re-open the issue if it doesn't solve it.
