### ISSUE TITLE
Name field in VMUserSpec

### ISSUE THREAD

**Issue by pavan541cs** [VictoriaMetrics/operator#472]
The name field passed for each user to vmauth is used in the label `username` for metrics `vmauth_user_requests_total` which will be useful to identify the source of the requests.

The documentation of victoriametrics states as below.
`vmauth` exports `vmauth_user_requests_total` metric with `username` label. The `username` label value equals to `username` field value set in the `-auth.config` file. It is possible to override or hide the value in the label by specifying `name` field. For example, the following config will result in `vmauth_user_requests_total{username="foobar"}` instead of `vmauth_user_requests_total{username="secret_user"}`

**Comment by pavan541cs** [comment]
@f41gh7 Can you let me know if there is any way to do the same so that I can proceed with the same. 
I am currently in process of implementation of vmauth and this feature is needed for the same.

**Comment by f41gh7** [comment]
For now it's not possible, will be added at the next release of operator.

**Comment by f41gh7** [comment]
lets keep it open until release.

**Comment by pavan541cs** [comment]
What is the plan for the next release? Any tentative dates? @f41gh7

**Comment by f41gh7** [comment]
I hope at the end of this week.

**Comment by pavan541cs** [comment]
@f41gh7 Any update on the release ?

**Comment by f41gh7** [comment]
Thank you for patience, changes was included into [v0.25.0 release](https://github.com/VictoriaMetrics/operator/releases/tag/v0.25.0)
