### ISSUE TITLE
Generate clientset for vm crds

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/operator#481]
Hi Team,
I'm trying to operate some crud in vm crd like vmrules, but can't find any client available now in project.
So I'm wondering why you guys not use tool like code-generator to generate clientset for them.
Thanks.

**Comment by f41gh7** [comment]
Hello,  you can use  kubernetes controller runtime client


  Example in pseudo-code, it may throw errors, it didn't test it. But it shows main concept. 
 
 go.mod
```
module my-module
go 1.18

require (
k8s.io/apimachinery v0.23.6
sigs.k8s.io/controller-runtime v0.11.2
github.com/VictoriaMetrics/operator/api v0.0.0-20220413082921-eef8e2eece26
k8s.io/client-go v12.0.0+incompatible
k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
)

replace (
	k8s.io/client-go => k8s.io/client-go v0.23.6
)
```

usage

```go
package main

import (
  "sigs.k8s.io/controller-runtime/pkg/client"
   operator "github.com/VictoriaMetrics/operator/api/v1beta1"
  "k8s.io/apimachinery/pkg/runtime"
"k8s.io/client-go/kubernetes/scheme"
"k8s.io/client-go/tools/clientcmd"
)

func setupRuntime() *runtime.Scheme {
	s := scheme.Scheme
	s.AddKnownTypes(operator.GroupVersion,
		&operator.VMRule{},
		&operator.VMRuleList{},
	)

	if err := operator.AddToScheme(s); err != nil {
		logger.Fatalf("BUG, cannot add scheme to client")
	}
	return s
}
func main(){
  
        lr := clientcmd.NewDefaultClientConfigLoadingRules()
	cfg := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(lr, &clientcmd.ConfigOverrides{})
	restCfg, err := cfg.ClientConfig()
	if err != nil {
		return nil, fmt.Errorf("cannot read client cfg from kubeconfig: %w", err)
	}

	c, err := client.NewWithWatch(restCfg, client.Options{Scheme: setupRuntime()})
	if err != nil {
		return nil, fmt.Errorf("cannot build client: %w", err)
	}
      var rules operator.VMRuleList
     if err := c.List(context.Background(), &rules); err != nil {
           logger.Fatalf("cannot list rules: %s",err)
     }
    for _, rule := range rules.Items{}
}
```

**Comment by Haleygo** [comment]
> Hello, you can use kubernetes controller runtime client
> 
> Example in pseudo-code, it may throw errors, it didn't test it. But it shows main concept.
> 
> go.mod
> 
> ```
> module my-module
> go 1.18
> 
> require (
> k8s.io/apimachinery v0.23.6
> sigs.k8s.io/controller-runtime v0.11.2
> github.com/VictoriaMetrics/operator/api v0.0.0-20220413082921-eef8e2eece26
> k8s.io/client-go v12.0.0+incompatible
> k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
> )
> 
> replace (
> 	k8s.io/client-go => k8s.io/client-go v0.23.6
> )
> ```
> 
> usage
> 
> ```go
> package main
> 
> import (
>   "sigs.k8s.io/controller-runtime/pkg/client"
>    operator "github.com/VictoriaMetrics/operator/api/v1beta1"
>   "k8s.io/apimachinery/pkg/runtime"
> "k8s.io/client-go/kubernetes/scheme"
> "k8s.io/client-go/tools/clientcmd"
> )
> 
> func setupRuntime() *runtime.Scheme {
> 	s := scheme.Scheme
> 	s.AddKnownTypes(operator.GroupVersion,
> 		&operator.VMRule{},
> 		&operator.VMRuleList{},
> 	)
> 
> 	if err := operator.AddToScheme(s); err != nil {
> 		logger.Fatalf("BUG, cannot add scheme to client")
> 	}
> 	return s
> }
> func main(){
>   
>         lr := clientcmd.NewDefaultClientConfigLoadingRules()
> 	cfg := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(lr, &clientcmd.ConfigOverrides{})
> 	restCfg, err := cfg.ClientConfig()
> 	if err != nil {
> 		return nil, fmt.Errorf("cannot read client cfg from kubeconfig: %w", err)
> 	}
> 
> 	c, err := client.NewWithWatch(restCfg, client.Options{Scheme: setupRuntime()})
> 	if err != nil {
> 		return nil, fmt.Errorf("cannot build client: %w", err)
> 	}
>       var rules operator.VMRuleList
>      if err := c.List(context.Background(), &rules); err != nil {
>            logger.Fatalf("cannot list rules: %s",err)
>      }
>     for _, rule := range rules.Items{}
> }
> ```

Thank you for the example :) 
Actually I'm using dynamicClient to operate them now, and all of these work. 
I just open this issue to ask that is there any thought to generate clientset for those crd(like [prometheus operator did](https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg/client/versioned/typed/monitoring/v1)), it will be much more convenient to use in another project.

**Comment by f41gh7** [comment]
It shouldn't be hard to implement it with https://github.com/kubernetes/code-generator

 Will ad it to backlog.

**Comment by Haleygo** [comment]
@f41gh7 Thanks for adding it.
I'm testing it now and found a bug that can't get all vm resources by client now. Because the request path prefix should be /apis instead of /api .
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/39937150/174720203-c0bbad50-bfdf-4262-b074-1523f9243872.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/39937150/174720382-48c3aef1-9a7c-4473-87a3-7b93dff3d214.png">
/api is only for k8s core [resource] (https://github.com/kubernetes/code-generator/blob/5a93c8bd8f9a2797d0fc9331b37614e7a9b149e4/cmd/client-gen/generators/generator_for_group.go#L75)
And I think the mistake is made by the input directory parameters when execute client-gen, code generator will use the directory path as api resource group.
<img width="948" alt="image" src="https://user-images.githubusercontent.com/39937150/174720771-42e3521a-1390-4799-9eae-d503bc138ee2.png">
Change file directory name from "core" to "vm" can fix it.

**Comment by f41gh7** [comment]
Thanks! Will fix it soon.

 I've just added generation and didn't test  it yet.

**Comment by f41gh7** [comment]
v0.26.0 release contains versioned client. It's moved into separate go module, which should reduce dependency blob. 

 Feel free to re-open, if it's not working.
