### ISSUE TITLE
vmstorage  and vmagent create statefulset mode pvc failed

### ISSUE THREAD

**Issue by cnych** [VictoriaMetrics/operator#482]
Warning  FailedCreate  94s (x12 over 105s)  statefulset-controller  create Pod vmstorage-vmcluster-0 in StatefulSet vmstorage-vmcluster failed error: failed to create PVC -vmstorage-vmcluster-0: PersistentVolumeClaim "-vmstorage-vmcluster-0" is invalid: metadata.name: Invalid value: "-vmstorage-vmcluster-0": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

VMAgent has the same question：

Warning  FailedCreate      14s (x15 over 96s)  statefulset-controller  create Pod vmagent-vmagent-0-0 in StatefulSet vmagent-vmagent-0 failed error: Pod "vmagent-vmagent-0-0" is invalid: spec.containers[1].volumeMounts[0].name: Not found: "persistent-queue-data"

Operator Version is  `v0.25.0`

**Comment by f41gh7** [comment]
Thanks, soon fix will be released.
