### ISSUE TITLE
VMAuth's EmbeddedIngress should have a host parameter

### ISSUE THREAD

**Issue by igorcoding** [VictoriaMetrics/operator#485]
Currently `EmbeddedIngress` does not allow specifying an ingress's host. Host will be added only if TlsHosts is defined (and source code proves that - https://github.com/VictoriaMetrics/operator/blob/87fe8c123363fa83024800a6168436637a151633/controllers/factory/vmauth.go#L408).

In our environment it is not possible to use https for vmauth's ingress and http is the only option, so it'll be great to have an ability to specify ingress host.

**Comment by f41gh7** [comment]
Included into v0.26.0 release
