### ISSUE TITLE
PrometheusRule deletion doesn't cause VMRule deletion

### ISSUE THREAD

**Issue by flokli** [VictoriaMetrics/operator#487]
I'm using `PrometheusRule` CRs to describe alerts, and `victoria-metrics-operator` created shadow-`VMRule` CRs before configuring a `vmalert` pod with it.

While this seems to mostly work, it seems the operator doesn't delete the `VMRule` CR if the `PrometheusRule` gets deleted.

So if someone uses `PrometheusRules` exclusively, delete alerts stay persisted in the vmalert config, until someone manually removes the `VMRule` CRs.

Can victoria-metrics-operator also delete `VMRule` CRs if the `PrometheusRule` CRs get deleted?

**Comment by f41gh7** [comment]
It should be possible with env variable for operator:

```
VM_ENABLEDPROMETHEUSCONVERTEROWNERREFERENCES=true
```

 In this case, operator creates ownerReference for each converted object and it will be removed with original CR.
