### ISSUE TITLE
QueueConfig not being referenced

### ISSUE THREAD

**Issue by tbuchier** [VictoriaMetrics/operator#491]
Hello,

QueueConfig Type mention that it's being referenced in the RemoteWriteSpec object:
https://github.com/VictoriaMetrics/operator/blob/d615023fdd2a81e87c08bfd416f8993bae5dba92/api/v1beta1/vmservicescrape_types.go#L458

But I can't find any reference of it in the code. 

VMAgentRemoteWriteSpec doesn't have a queue_config parameter as mentioned here: https://docs.victoriametrics.com/operator/api.html#queueconfig
 
https://github.com/VictoriaMetrics/operator/blob/d615023fdd2a81e87c08bfd416f8993bae5dba92/api/v1beta1/vmagent_types.go#L404

**Comment by f41gh7** [comment]
Hello, such configuration options not applied for `VMAgent`, thanks for spotting it. This struct must be removed.

**Comment by f41gh7** [comment]
removed dead code, thanks for pointing.
