### ISSUE TITLE
How to fix VMCluster status in expanding at a very very long time.

### ISSUE THREAD

**Issue by leonatone** [VictoriaMetrics/operator#493]
Can anybody help me me~.

### victoriametrics operator version:
**v0.24.0**
### Case
After Creating a VMCluster with 2 select ,2 storage ,2insert.
We got Vmcluster status: expanding for a very very long time , about 18h-2days.
Here is my operator log:
### Log
**{"level":"info","ts":1655985905.076249,"logger":"controller_vmcluster","msg":"requeuing cluster expanding with back-off","Request.Namespace":"test","Request.Name":"vm-dd40f4","fail update count":0,"after":"0s"}**

Since above log, the operator do not update VMCluster status to "operational" forever except Rebooting The Operator.

And ony 10% of my cluster instance can go to "operational".

**Comment by leonatone** [comment]
The instance vm-dd40f4 is actually OK when "the log" happends.  
All pods are avaliable and can supply correct service.

**Comment by f41gh7** [comment]
v0.26.0 release must fix this issue and make status more reliable.

**Comment by f41gh7** [comment]
Feel free to re-open if fix doesn't help.
