### ISSUE TITLE
Is VMAgent has job sample_limit prometheus metric?

### ISSUE THREAD

**Issue by hellorill** [VictoriaMetrics/operator#497]
Is it possible to get sample_limit per job as prometheus metrics? One way is to request /config and parse it (write custom config exporter or smth). This is necessary to determine, which containers/daemons write more metrics than sample_limit. We have scrape_samples_scraped but no scrape_samples_limit.

**Comment by valyala** [comment]
@hellorill , `vmagent` will push the `scrape_samples_limit` metric for targets with non-zero `sample_limit` option to the configured remote storage starting from the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c66f676f3b3ddcbd649b209fff575b994fb196d8 . This commit will be included in the next release of `vmagent`. In the meantime you can build `vmagent` from this commit according to [these instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether it works as expected.

**Comment by valyala** [comment]
FYI, `vmagent` generates and pushes the `scrape_samples_limit` metric per each scrape target with non-zero `sample_limit` option starting from [v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by f41gh7** [comment]
@valyala  thanks!
