### ISSUE TITLE
Add global setting to override container registry

### ISSUE THREAD

**Issue by tamcore** [VictoriaMetrics/operator#498]
Currently it's required to set 

- VM_VMALERTDEFAULT_IMAGE
- VM_VMAUTHDEFAULT_IMAGE
- VM_VMAGENTDEFAULT_IMAGE
- VM_VMBACKUP_IMAGE
- VM_VMSINGLEDEFAULT_IMAGE
- VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE
- VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE
- VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE
- VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE
- VM_VMALERTDEFAULT_CONFIGRELOADIMAGE

individually to point to a registry cache. It would be nice to have a simple setting like `VM_CONTAINERREGISTRY` or something to override the current default of `docker.io`.

**Comment by f41gh7** [comment]
Added to the v0.26.0 release, thanks for contribution!
