### ISSUE TITLE
deploy  release v0.28 crds. The CustomResourceDefinition "vmalerts.operator.victoriametrics.com" is invalid: 

### ISSUE THREAD

**Issue by bangbangzheng** [VictoriaMetrics/operator#520]
in k8s v1.20 v1.22 deploy  release v0.28 crds

[root@iot-factory-master-01 ~]# kubectl apply -f release/crds
customresourcedefinition.apiextensions.k8s.io/vmagents.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmalertmanagerconfigs.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmalertmanagers.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmauths.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmclusters.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmnodescrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmpodscrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmprobes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmrules.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmservicescrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmsingles.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmstaticscrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmusers.operator.victoriametrics.com created
The CustomResourceDefinition "vmalerts.operator.victoriametrics.com" is invalid:

spec.validation.openAPIV3Schema.properties[spec].properties[datasource].properties[headers].allOf[0].items.type: Forbidden: must be empty to be structural
spec.validation.openAPIV3Schema.properties[spec].properties[datasource].properties[headers].allOf[1].items.type: Forbidden: must be empty to be structural
spec.validation.openAPIV3Schema.properties[spec].properties[datasource].properties[headers].items: Required value: must be specified
spec.validation.openAPIV3Schema.properties[spec].properties[remoteWrite].properties[headers].allOf[0].items.type: Forbidden: must be empty to be structural
spec.validation.openAPIV3Schema.properties[spec].properties[remoteWrite].properties[headers].allOf[1].items.type: Forbidden: must be empty to be structural
spec.validation.openAPIV3Schema.properties[spec].properties[remoteWrite].properties[headers].items: Required value: must be specified

**Comment by bangbangzheng** [comment]
in k8s v1.20  v1.22

[root@iot-factory-master-01 ~]# kubectl apply -f release/crds
customresourcedefinition.apiextensions.k8s.io/vmagents.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmalertmanagerconfigs.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmalertmanagers.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmauths.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmclusters.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmnodescrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmpodscrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmprobes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmrules.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmservicescrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmsingles.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmstaticscrapes.operator.victoriametrics.com created
customresourcedefinition.apiextensions.k8s.io/vmusers.operator.victoriametrics.com created
The CustomResourceDefinition "vmalerts.operator.victoriametrics.com" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[datasource].properties[headers].allOf[0].items.type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[datasource].properties[headers].allOf[1].items.type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[datasource].properties[headers].items: Required value: must be specified
* spec.validation.openAPIV3Schema.properties[spec].properties[remoteWrite].properties[headers].allOf[0].items.type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[remoteWrite].properties[headers].allOf[1].items.type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[spec].properties[remoteWrite].properties[headers].items: Required value: must be specified

**Comment by f41gh7** [comment]
sry, must be fixed at 0.28.1

**Comment by bangbangzheng** [comment]
> sry, must be fixed at 0.28.1

It's too timely! Thank you so much.

**Comment by f41gh7** [comment]
Correct version must be at v0.28.3 - feel free to re-open if issue not fixed.
