### ISSUE TITLE
refactor auth options for components

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#522]
Unify auth options with HTTPAuth.
Check the following:
1) Check basicAuth correctly uses passwordFile option.
2) OAuth2 - adds it for remote options
3) bearerToken - add for remote options

**Comment by Haleygo** [comment]
@f41gh7 
I'd like to divide this into following tasks:

- [ ] unify `oauth2` field tag with "oauth2"
Will introduce breaking change in vmalert config, now using "OAuth2".
- [ ] modify `TokenFilePath` under BearerAuth with "bearerTokenFile", the same with others under scrape objects.
Will introduce breaking change in vmalert config, now using "bearerTokenFilePath".
- [ ] unify/implement HTTPAuth for vmagent.remoteWriteSpec, scrape objects...
Shouldn't introduce any breaking change to user.

**Comment by hagen1778** [comment]
@Haleygo could you please update me on the state of this ticket?
