### ISSUE TITLE
support multi-arch as part of release.

### ISSUE THREAD

**Issue by JaredTan95** [VictoriaMetrics/operator#541]
I noticed that there is something crosscompile scripts in`Makefile` , but , it looks like not working at dockerhub https://hub.docker.com/r/victoriametrics/operator/tags?page=1&name=arm :
<img width="864" alt="企业微信截图_470a561b-d388-40a7-84e3-89f12df96088" src="https://user-images.githubusercontent.com/12468337/196852660-e4ef2baf-2ef6-4dd2-ac58-8fb3a9204858.png">

So, I think we need to polish the `CI` workflow to fix it.
And I'd like to fix it. :-P

**Comment by f41gh7** [comment]
Well, it should be re-worked. Currently docker-manifest is used for docker image packaging. Need to switch for buildx https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/Makefile#L74

 I'll take a look later.

**Comment by Haleygo** [comment]
Should be fixed by https://github.com/VictoriaMetrics/operator/pull/681.
@f41gh7 Should we release v0.34.2?

**Comment by f41gh7** [comment]
Yes, I'll perform few regression tests and I hope to release new version at Friday.
