### ISSUE TITLE
Update field currentRevision in StatefulSets created by operator

### ISSUE THREAD

**Issue by imcitius** [VictoriaMetrics/operator#547]
Hello!

Due to operator not updating `currentRevision` field in accordance with `updateRevision` after STS upgrades, kube-state-metrics's `kube_statefulset_status_replicas_current` metric is showing incorrect value.
Please consider to add this to operator's logic.

These 2 issues has more details:
https://github.com/kubernetes/kube-state-metrics/issues/1324
https://github.com/Opster/opensearch-k8s-operator/issues/310

Thanks!

**Comment by hagen1778** [comment]
@f41gh7 @k1rk @zekker6 would appreciate your feedback!

**Comment by f41gh7** [comment]
Must be fixed at v0.29.1 release, feel free to re-open

**Comment by imcitius** [comment]
Hi!

Sorry, dos'nt seems to be fixed. :(

I've set set `images.tag` to `v0.29.1` in vm-operator helm release, and operator version is current:
```❯ kubectl describe pod vm-operator-victoria-metrics-operator-cd5f8694c-sprqf -n cluster-services | grep Image
    Image:         victoriametrics/operator:v0.29.1
    Image ID:      docker.io/victoriametrics/operator@sha256:bf18861fe0400e80206cfe0a98f255e024c3b39f56e34a018eb9381e7535110b
```
Current status of VmAlertManager STS:
```status:
  collisionCount: 0
  currentRevision: vmalertmanager-infra-monitoring-85d6777cc7
  observedGeneration: 3
  readyReplicas: 2
  replicas: 2
  updateRevision: vmalertmanager-infra-monitoring-5c46dd5df6
  updatedReplicas: 2
```

Chaned `replicas` value in corresponding VmAlertManager object, updated status does'nt have correct ... field:
```status:
  collisionCount: 0
  currentRevision: vmalertmanager-infra-monitoring-85d6777cc7
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updateRevision: vmalertmanager-infra-monitoring-9cc95f89
```

`currentRevision` field still indicates some old value.

**Comment by imcitius** [comment]
Fixed now, thanks!
