### ISSUE TITLE
CPU limits should be removed

### ISSUE THREAD

**Issue by jgillich** [VictoriaMetrics/operator#553]
I'm using the k8-stack helm chart to deploy VictoriaMetrics and I noticed that I regularly get `CPUThrottlingHigh` alerts on the vmagent pod. This is because there is a default cpu limit of 100m, despite never having set one myself.

CPU limits serve no purpose and are generally harmful, see https://home.robusta.dev/blog/stop-using-cpu-limits

AFAIK there isn't a way to remove the limit, only to raise it. I think it would be best to remove the default CPU limits.

If I'm correct, the change needs to be made here https://github.com/VictoriaMetrics/operator/blob/5c66fc6baebef5157a1e12332d86e6cb1fe64af8/internal/config/config.go#L60

**Comment by leo-minorui** [comment]
you can close the alert or raise cpu。 I think using cpu-limits is good and safe for prod env。

**Comment by f41gh7** [comment]
Hello, defaults limits could be removed via env vars for operator per CRD object, for instance:

VM_VMALERTDEFAULT_USEDEFAULTRESOURCES=false

 Removes default resources for vmalert, more env vars could be found at:

https://github.com/VictoriaMetrics/operator/blob/master/vars.MD
