### ISSUE TITLE
custom image and tag based on alertmanager cannot work well

### ISSUE THREAD

**Issue by leo-minorui** [VictoriaMetrics/operator#555]
operator version: v0.29.1

when I have migraged monitor from kube-prometheus to VMoperator, I find alertmanage cannot start.
After debug, I find  `tag version`  is the cause 。I use custom Image based on version v0.24.0 on alertmanager and named xxxx/monitoring/alertmanager:v0.1.5. And after I renamed to v1.0.0, it worked well。

It doesn't seem to take into account the case of custom mirror

**Comment by leo-minorui** [comment]
I  try to changed the source code :
`if amVersion != nil && cr.Spec.Image.Repository == "prom/alertmanager"` 
works well when use xxx/monitoring/alertmanager:v0.1.5

Is that intentional? If so, I will close the issue. If not, whether to consider my thoughts

**Comment by f41gh7** [comment]
Hello, can you try to keep the same version and change your image for xxxx/monitoring/alertmanager:v0.24.0?

  Operator tries to detect alertmanager version and changes args for it according to the version.

 Proposed changes breaks backward compatibility and may affect other users.

**Comment by leo-minorui** [comment]
I have tried , it works well. But when I name version to v0.1.5, Operator will change args from `--cluster` to `--mesh` `--` to `-`. And alertmanager on v0.24.0 cannot start with  args  `-`

**Comment by f41gh7** [comment]
> I have tried , it works well. But when I name version to v0.1.5, Operator will change args from `--cluster` to `--mesh` `--` to `-`. And alertmanager on v0.24.0 cannot start with args `-`

 Yes, it's expected behavior, those changes made for backward compatibility with older alertmanager versions.

**Comment by leo-minorui** [comment]
fine, for compatibility.
