### ISSUE TITLE
VMAlertmanagerConfig add more sanity checks

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#560]
First of all, make validation for secret urls, it must be correct url. 

 Second, add validation for correct receiver names at routes and time intervals.

  Examples could be found at alertmanager repo https://github.com/prometheus/alertmanager/blob/6ef6e6868dbeb7984d2d577dd4bf75c65bf1904f/config/config.go#L317

**Comment by Haleygo** [comment]
/assign
I will work on it :)
