### ISSUE TITLE
VMSelectHPA uses the VMInsertLabels

### ISSUE THREAD

**Issue by yimenghua** [VictoriaMetrics/operator#562]
/controllers/factory/vmcluster.go
createOrUpdateVMSelectHPA
row 1364
In this func it should be **VMSelectSelectorLabels()** not **VMInsertSelectorLabels()**
```go
defaultHPA := buildHPASpec(targetRef, cluster.Spec.VMSelect.HPA, cluster.AsOwner(), cluster.VMInsertSelectorLabels(), cluster.Namespace)

**Comment by f41gh7** [comment]
Thanks for pointing, will be fixed soon.

**Comment by f41gh7** [comment]
Was added at the v0.30.0 release
