### ISSUE TITLE
Provide crd.yaml as part of the release

### ISSUE THREAD

**Issue by avthart** [VictoriaMetrics/operator#565]
We would like to to have the `crd.yaml` file as part of an release.

This makes it easier to install or use the crds directly (e.g. using kustomize or openapi2jsonschema), instead of downloading an unpacking the zip file first.

**Comment by avthart** [comment]
Created a PR to support this:
https://github.com/VictoriaMetrics/operator/pull/566

**Comment by f41gh7** [comment]
Must be fixed at v0.30.1 release and now crd.yaml published at release page.
