### ISSUE TITLE
Is there a way to completely disable scrapping on vmagent, I only want to use it for pushing

### ISSUE THREAD

**Issue by whitehatbuds** [VictoriaMetrics/operator#568]

**Comment by whitehatbuds** [comment]
I've disabled scrapping from vmagent but someone the up{} metric is being automatically generated in victoria-metrics for some scrape targets

**Comment by whitehatbuds** [comment]
my vmagent spec consist of these values only
spec:
  arbitraryFSAccessThroughSMs: {}
  image:
    repository: victoriametrics/vmagent
    tag: v1.79.3
  insertPorts:
    openTSDBHTTPPort: "4242"
  remoteWrite:
  - url: http://vminsert-vm-cluster.victoria-metrics-byteyard.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
  replicaCount: 1
  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2G

**Comment by Amper** [comment]
Hi @whitehatbuds.
Is your question still relevant?
