### ISSUE TITLE
VMAgent supports auto scaling for shardCount

### ISSUE THREAD

**Issue by acmicrox** [VictoriaMetrics/operator#570]
One of the great features of VM is that vmagent can support to scrape a big number of targets. With VM operator, one can easily achieve this by adjusting the value of shardCount in the VMAgent spec. However, in our use case, the number of targets is not only big but also varied significantly during peak hours and off-peak hours. Thus, if VM operator can support auto-scaling for shardCount, it will help us to save costs. Please consider to support this feature that shall be beneficial for a number of users.

**Comment by f41gh7** [comment]
Was added at the v0.30.0 release

**Comment by togikiran** [comment]
@f41gh7 
1) Why the vmagent pods are getting rotated whenever we are increasing the replica-count ?
Command used: `kubectl scale vmagent-shard-ha --replicas=3` 

2) How should we configure hpa to scale based on cpu/memory utilisation ?
`apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: vmagent-shard-ha
    app.kubernetes.io/name: vmagent-shard-ha
  name: vmagent-shard-ha
  namespace: victoria-metrics
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: operator.victoriametrics.com/v1beta1
    kind: VMAgent
    name: vmagent-shard-ha`
    
    What the above hpa scaling metric is showing unknow 
    `NAME                    REFERENCE                       TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
monitoring-vmagent-ha   VMAgent/ vmagent-shard-ha`  <unknown>/80%   3         3         3          14m`

**Comment by akasprzok** [comment]
Running into the same problem here. Not sure what the HPA should look like.
