### ISSUE TITLE
VMOperator workqueue full

### ISSUE THREAD

**Issue by zhulaker** [VictoriaMetrics/operator#575]
all the edit for vmcluster will be delay to about 10 hours.
when I look into vm-operator metrics, I found  meitrcs[ workqueue_depth] is like below
<img width="1104" alt="图片" src="https://user-images.githubusercontent.com/20249430/209925293-3a091431-36fe-430c-813c-e2539df03f2e.png">
<img width="1080" alt="图片" src="https://user-images.githubusercontent.com/20249430/209927707-29af708a-db6e-4b15-acc2-653fa968fe42.png">

and it seems 

we do have about 8000 vmrules in our cluster, but we never change it all ever.

is there a way that we can consume this vmrule queue more quickly? or can we know why we have such amount of vmrules event every several houts

**Comment by f41gh7** [comment]
Well, each queue must be processed independently by controller. There is also rateLimiter, that helps to process similar objects faster. Probably, bottleneck is somewhere else.

 Probably, there is an issue with CPU and consumption? Can you check it? CPU profile could be useful in this case for optimizations.

 Also, there is latency metrics for items processing, maybe there is something interesting.

**Comment by zhulaker** [comment]
Actually operator cpu usage is just about 10%, i think cpu is not the issue
<img width="1101" alt="图片" src="https://user-images.githubusercontent.com/20249430/210122339-b0dc6a05-9a91-43f6-818a-1699a3a54812.png">


By the way, we do have same vmrules in different namesapce, is it possible that where will be some conflict on it?

**Comment by zhulaker** [comment]
and I also find that log in operator is full of vmrule.

**Comment by zhulaker** [comment]
And I also find the logs is full of vmrule, but I am sure there is no change during this period

**Comment by zhulaker** [comment]
And I also find the logs is full of vmrule, but I am sure there is no change during this period   
![图片](https://user-images.githubusercontent.com/20249430/210122463-805ee5a1-bdaf-4b84-ad52-4eeb5ee9f3f1.png)

**Comment by f41gh7** [comment]
@zhulaker  at the v0.30.1 release was added new flag `controller.maxConcurrentReconciles=1`. I'd recommend to increase value for it up to 30-40. It should improve performance at large scale.  Let me know if it doesn't help.

**Comment by hagen1778** [comment]
Closing as stale. Feel free to re-open
