### ISSUE TITLE
VMAuth's Auto-Created VMServiceScrape Reconciliation

### ISSUE THREAD

**Issue by mohammadkhavari** [VictoriaMetrics/operator#579]
VMAuth's controller in spite of other controllers does not owns (watch for) its auto-created VMSeriviceScrape as a resource for the reconciliation loop, So as far as I've tested if you delete servicescrape of a vmsingle, servicescrape will be recreated but there's no such behavior for vmauth.
code references:

https://github.com/VictoriaMetrics/operator/blob/93c9e780981ceb6869ee2953056a9bd3b6e6eae7/controllers/vmauth_controller.go#L113

https://github.com/VictoriaMetrics/operator/blob/93c9e780981ceb6869ee2953056a9bd3b6e6eae7/controllers/vmsingle_controller.go#L119

**Comment by f41gh7** [comment]
Thanks fixed at v0.30.1 release
