### ISSUE TITLE
question: how to enable operator ready state after all sub conponents starts?

### ISSUE THREAD

**Issue by Howie59** [VictoriaMetrics/operator#581]
as topic describe

**Comment by Howie59** [comment]
any method like this?
`kubectl - wait - --for=condition=Ready `

**Comment by f41gh7** [comment]
It's an interesting feature. Currently, only VMCluster has correct status spec that reflects actual cluster status.

 Usually I recommend to wait for specific deployments/pods created by operator instead of waiting for CRD status.
