### ISSUE TITLE
FR: Add templates field to VMAlertmanagerConfigSpec CRD

### ISSUE THREAD

**Issue by zorgzerg** [VictoriaMetrics/operator#590]
It is not possible pass a list of files with message templates by defining the configuration for the alertmanager using CR `VMAlertmanagerConfig`.

Add `templates[]` to the `VMAlertmanagerConfigSpec` please
See https://prometheus.io/docs/alerting/latest/configuration/#configuration-file

**Comment by f41gh7** [comment]
Well, I was thinking about adding it recently. But it's not trivial and insecure. It may break alertmanager's configuration file and disrupt service for all users.

  I strongly recommend to keep templates as part of `VMAlertmanager` and provide it's API to the `VMAlertmanagerConfigSpec` users.

**Comment by f41gh7** [comment]
Since v0.31.0  `VMAlertmanager` supports templates reference. It cannot be added to the VMAlertmanagerConfig as I mentioned before.
