### ISSUE TITLE
alertmanager templates changed not trigger config reload 

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/operator#592]
I have configured a directory for storing Alertmanager templates. It was created as a ConfigMap mounted into `/etc/vm/configs/<configmap-name>`.  When I only modified these templates, the sidecar configmap-reload was not triggered to work.
I see the args of configmap-reload, it only watches a fixed directory `/etc/alertmanager/config`. I could not add another directory.
What could I do for triggering automatic Alertmanager reload when I change these templates?
Could vm-operator support a custom configmap-reload configuration?
Thanks.

**Comment by okzheng** [comment]
Thanks~

**Comment by f41gh7** [comment]
Since v0.31.0  `VMAlertmanager` supports templates reference. Need to add docs for it.
