### ISSUE TITLE
why not create client for VMAlertmanagerConfig and VMAUTH

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/operator#599]
https://github.com/VictoriaMetrics/operator/issues/481 had done the work using [code-generator](https://github.com/kubernetes/code-generator) to generate client for the vm's crd. But types like VMAlertmanagerConfig and VMAuth don't have the "//+genclient" tag to create client. 
![image](https://user-images.githubusercontent.com/39937150/222391907-1de5b201-c964-4cdd-8083-0b9290e46692.png)

I am wondering why, can they be added now?
![image](https://user-images.githubusercontent.com/39937150/222391504-30382532-52de-42f6-b72d-b9ae8864e675.png)

**Comment by f41gh7** [comment]
Must be fixed at v0.31.0 version
