### ISSUE TITLE
[vmcluster]: Why only expanded pvc？

### ISSUE THREAD

**Issue by z-anshun** [VictoriaMetrics/operator#600]
When I expand the resource request of vmcluster about vmstorage, it only expands the capacity of pvc, and pv does not change.
Then I read the following code, it only expands pvc, but not pv. I don't know if I should add the expansion of pv?

https://github.com/VictoriaMetrics/operator/blob/132cb49e7b8703c29d25e8ac9e32deedb47bf690/controllers/factory/k8stools/expansion.go#L217-L230

**Comment by f41gh7** [comment]
It's assumed that persistent volume is dynamically provisioned and will be resized by storage provider (aws csi-controller or any other). So in this case it's enough to modify claim.

 More info about kubernetes volumes https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic

**Comment by z-anshun** [comment]
thanks, @f41gh7 . I know why I only expanded the persistent volume, because I'm using `local-path` as storage provider, which does not support volume expansion. But do we need to add logs to warn that the storage provider does not support volume expansion (by comparing `status.capacity.storage` and `spec.resources.requests.storage`).

**Comment by z-anshun** [comment]
I understand, thank you very much! @f41gh7
