### ISSUE TITLE
Support `Silence` CRD

### ISSUE THREAD

**Issue by cskinfill** [VictoriaMetrics/operator#601]
It would be great to add a `Silence` CRD that could be used to create a alertmanager `Silence` using a kubernetes resource.  See for an similar tool https://github.com/giantswarm/silence-operator.

**Comment by f41gh7** [comment]
I'm not sure that I get the point of this CRD. Usually alerts silenced via alertmanager web-ui or any alert manager tools by human, it's not needed to create CR object for this case.
