### ISSUE TITLE
release v0.32.0 breaking deployments

### ISSUE THREAD

**Issue by td-raystevens** [VictoriaMetrics/operator#608]
A typo made here
https://github.com/VictoriaMetrics/operator/commit/b49e7d6e2ebf0a2cf8aced962ffb01f1427fd0db

results in failure for pods to deploy

**Comment by f41gh7** [comment]
Will release a patch for it soon.

**Comment by td-raystevens** [comment]
Can you release in the community operator?
https://github.com/redhat-openshift-ecosystem/community-operators-prod/commits/main/operators/victoriametrics-operator

**Comment by f41gh7** [comment]
Was released at operatorhub. Sry for breaking changes.
