### ISSUE TITLE
add compatability info

### ISSUE THREAD

**Issue by floppy-engineer** [VictoriaMetrics/operator#61]
Hi,

Please add compatibility info to your docs. 
Currently, your crd.yaml (v0.1.0) doesn't work in openshift 3.11 and kubernetes 1.18.5

for k8s_1.18.5:
customresourcedefinition.apiextensions.k8s.io/vmclusters.operator.victoriametrics.com configured
customresourcedefinition.apiextensions.k8s.io/vmpodscrapes.operator.victoriametrics.com configured
customresourcedefinition.apiextensions.k8s.io/vmrules.operator.victoriametrics.com configured
customresourcedefinition.apiextensions.k8s.io/vmservicescrapes.operator.victoriametrics.com configured
Error from server (Invalid): error when creating "release/crds/crd.yaml": CustomResourceDefinition.apiextensions.k8s.io "vmagents.operator.victoriametrics.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
Error from server (Invalid): error when creating "release/crds/crd.yaml": CustomResourceDefinition.apiextensions.k8s.io "vmalertmanagers.operator.victoriametrics.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
Error from server (Invalid): error when creating "release/crds/crd.yaml": CustomResourceDefinition.apiextensions.k8s.io "vmalerts.operator.victoriametrics.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
Error from server (Invalid): error when creating "release/crds/crd.yaml": CustomResourceDefinition.apiextensions.k8s.io "vmsingles.operator.victoriametrics.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]

**Comment by f41gh7** [comment]
That's for report. 

It's a regression at crd generation script (previous issue)[https://github.com/VictoriaMetrics/operator/issues/37]. We've tested operator with k8s version from 1.13 to 1.18 and it works.

 I'll update compatibility matrix at readme and release patch soon.

**Comment by f41gh7** [comment]
must be fixed at v0.1.1 
https://github.com/VictoriaMetrics/operator/releases/download/v0.1.1/bundle_crd.zip

 If you spot some other problems with 1.18, let me know.

**Comment by floppy-engineer** [comment]
sure. thanks
