### ISSUE TITLE
Support vmagent shard awarness

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/operator#611]
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4018

Both of the proposed solutions will require operator to automatically configure the command-line flags to populate them with cluster member addresses.

**Comment by hagen1778** [comment]
Blocked by https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4018

**Comment by Haleygo** [comment]
@hagen1778 Since https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4018 is completed by displaying all the discovered targets at the http://vmagent:8429/service-discovery page, should we close this one?

**Comment by hagen1778** [comment]
>  should we close this one?

Yes! Thank you @Haleygo !
