### ISSUE TITLE
vmagent: expose each shard of the cluster under different address/service name

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/operator#612]
When in [cluster mode](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets), vmagent splits the list of targets among the configured shards. One shard starts to scrape only 1/N fraction of all configured targets, and so it shows on /targets page as well.

Each vmagent shard has its own share of targets to scrape. But there is no way to view to the global list of all configured targets via UI.

The issue can be solved via https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4018

As workaround, each shard of vmagent cluster can be exposed under different service name, so user can have access to all vmagent shards and check their UIs manually.

**Comment by f41gh7** [comment]
This work-around is out of the goal of `operator` configuration. vmagent exposed via external `Ingress` rule not managed by operator.

 I'll add an examples later, but it's better to wait for actual implementation at vmagent ui for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4018.

**Comment by f41gh7** [comment]
Closing since linked issue was resolved at vmagent side.
