### ISSUE TITLE
remove hardcoded namespace default

### ISSUE THREAD

**Issue by floppy-engineer** [VictoriaMetrics/operator#62]
Hi,
Please remove hardcoded namespace=default from you rbac.yaml and manager.yaml
Operator should has the possibility to be installed into any namespace of user's choose.
Thanks

**Comment by f41gh7** [comment]
Hello, 

 What is your operator deployment tool? kubectl or something else?

 This was done for quick namespace replacement with sed. For instance you can apply  command: ```sed -i "s/namespace: default/namespace: mon/g" operator_dir/*.yaml && kubectl apply -f operator_dir/``` and it  will replace default namespace  and install operator at desired namespace.
 Without it, you have to specify namespace directly and clusterRoleBinding.

 I expect helm chart to be released soon. It will simply deployment and solve such problems. 

 Another approach - using kustomize with patch.

**Comment by floppy-engineer** [comment]
Yes, kubectl.
Thanks, I know such tricks and it's not a problem to change it in yaml anyway. My point was to prevent things like accidentelly mangling a default namespace when installing according your docs without examine the code itself)

**Comment by f41gh7** [comment]
I will add this tip at quick-start docs.

**Comment by elmariofredo** [comment]
Can we rename namespace from default to `monitoring-system`? I agree that having `default` as namespace doesn't make much sense, but rather than not having any namespace I would prefer to have one predefined.

**Comment by f41gh7** [comment]
May be `monitoring` is better? 

 For me, there is no difference, I always change it. 

  But it requires one more step into quick-start docs and may confuse some people (default namespace always exists at Kubernetes cluster). 

 And I assume, that `helm install --namespace monitoring victoriametrics/operator` or `kustomize build && kubectl apply -f -` would solve such problems. May be I'm wrong.

**Comment by elmariofredo** [comment]
There is actually trend to keep cluster critical components in namespaces named with `-system` suffix ( e.g. https://metallb.universe.tf/installation/#installation-by-manifest ) but it's up to each maintainer to decide what is their preferred naming style. I believe that we have now namespace as part of manifests so no matter what we name it, it will get created for users without any additional steps. Let me know if you up to change and I can send MR either monitoring or monitoring-system both is absolutely fine with me as long as it's not default 😉

**Comment by f41gh7** [comment]
It sounds reasonable. Thanks for explanation. Lets rename it to monitoring-system )

**Comment by elmariofredo** [comment]
Here is MR https://github.com/VictoriaMetrics/operator/pull/81

**Comment by floppy-engineer** [comment]
Sorry for delay. I'll check when it comes to a release.

**Comment by f41gh7** [comment]
FYI, helm chart was released https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator
