### ISSUE TITLE
Set readOnlyRootFilesystem to true for all containers

### ISSUE THREAD

**Issue by timp87** [VictoriaMetrics/operator#637]
My proposal is to set (hardcode) readOnlyRootFilesystem to true by operator for all containers [securityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core). For example prometheus-operator currently deploys the stack with hardcoded readOnlyRootFilesystem in container's securityContext. I. e. it hardcodes this option for all resources deployed withing CRs.

I find this option as a nice security measure and in my experience many companies enforce this setting to be on for all containers.

**Comment by f41gh7** [comment]
Also it'd be great to add `PodSecurityContext` https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod.

 It has really nice feature `fsGroupChangePolicy`. https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

```
By default, Kubernetes recursively changes ownership and permissions for the contents of each volume to match the fsGroup specified in a Pod's securityContext when that volume is mounted. For large volumes, checking and changing ownership and permissions can take a lot of time, slowing Pod startup.
```

 It should simplify managing volume permissions. 

 cc @Amper  @hagen1778

**Comment by uhthomas** [comment]
I agree, this was also my proposal in https://github.com/VictoriaMetrics/operator/pull/692#issuecomment-1648256933

**Comment by Haleygo** [comment]
PodSecurityContext already added in https://github.com/VictoriaMetrics/operator/pull/692.
As for `fsGroupChangePolicy: OnRootMismatch`, I need to do some research on default fs group for pod volume, see if it's necessary here.

**Comment by Haleygo** [comment]
[Strict SecurityContext](https://github.com/VictoriaMetrics/operator/blob/master/internal/config/config.go#L271) will be added by default since [v0.36.0 ](https://github.com/VictoriaMetrics/operator/releases/tag/v0.36.0), users can disable it by setting `VM_ENABLESTRICTSECURITY=false`.
If SecurityContext already defined before for pod or containers, the default Strict SecurityContext won't be applied too.

Close this as completed.
