### ISSUE TITLE
how to use vmoperator without cluster scope permissions

### ISSUE THREAD

**Issue by SaschaP95** [VictoriaMetrics/operator#641]
Hello together

I'm working in a bigger company with a K8s as a Service platform. We order a K8s cluster and get a managed one.
This works fine but has limited permissions and dont allow everything.
I my case its only allowed to have more then get, list and watch permission on cluster scope level and in clusterroles.
Therefore i rewrite the vm-operator deployment to fulfill the RBAC concept.

I have clusterroles with get, list and watch permissions and a role with create, delete, etc. permission in each namespace.
I also configured the _WATCH_NAMESPACE_ env flag in the deployment.

Now the problem starts. I can deploy thats no problem but I get some errors in the vm-operator logs.

`{"level":"error","ts":1683637397.9190826,"msg":"k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:169: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User \"system:serviceaccount:XXXX:vm-operator\" cannot list resource \"storageclasses\" in API group \"storage.k8s.io\" at the cluster scope\n","stacktrace":"k8s.io/klog/v2.(*loggingT).output\n\tk8s.io/klog/v2@v2.80.1/klog.go:874\nk8s.io/klog/v2.(*loggingT).printDepth\n\tk8s.io/klog/v2@v2.80.1/klog.go:714\nk8s.io/klog/v2.ErrorDepth\n\tk8s.io/klog/v2@v2.80.1/klog.go:1534\nk8s.io/apimachinery/pkg/util/runtime.logError\n\tk8s.io/apimachinery@v0.25.6/pkg/util/runtime/runtime.go:115\nk8s.io/apimachinery/pkg/util/runtime.HandleError\n\tk8s.io/apimachinery@v0.25.6/pkg/util/runtime/runtime.go:109\nk8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\tk8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:140\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\tk8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:224\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:157\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:158\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\tk8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:222\nk8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:58\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\tk8s.io/apimachinery@v0.25.6/pkg/util/wait/wait.go:75"}`

Also its not possible to delete a deployment 

`{"level":"error","ts":1683637889.7690547,"msg":"Reconciler error","controller":"vmcluster","controllerGroup":"operator.victoriametrics.com","controllerKind":"VMCluster","VMCluster":{"name":"vmcluster-kustomization-test","namespace":"kustomization-test"},"namespace":"kustomization-test","name":"vmcluster-kustomization-test","reconcileID":"f212f39d-f811-4e77-9351-f483b04278e3","error":"clusterrolebindings.rbac.authorization.k8s.io \"vmcluster-vmcluster-kustomization-test\" is forbidden: User \"system:serviceaccount:XXXX:vm-operator\" cannot delete resource \"clusterrolebindings\" in API group \"rbac.authorization.k8s.io\" at the cluster scope","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}`

Is it possible to run the vm-operator without cluster scope permissions?

**Comment by f41gh7** [comment]
Hello, I think for now, it's not possible. We'll address this issue and fix it the next release.

**Comment by SaschaP95** [comment]
Hey
this would be great thanks alot.
can you roughly estimate how long it would take?
At the moment we have a special agreement to run it with permissions on cluster scope. but is agreement is not forever. We are forced to change it.

**Comment by f41gh7** [comment]
> Hey
> this would be great thanks alot.
> can you roughly estimate how long it would take?
> At the moment we have a special agreement to run it with permissions on cluster scope. but is agreement is not forever. We are forced to change it.

Hello, it requires a bit more time, that I expect. Probably at the end of this week.

**Comment by f41gh7** [comment]
An example of minimal needed permissions for single namespace https://github.com/VictoriaMetrics/operator/pull/647/files#diff-7b4c650e6639c0c6ce725a2d295ea332155e956c8e28016f7ee16d5d4e318910

**Comment by SaschaP95** [comment]
Wow thanks for the fast change.
Is there a way to test it ?

**Comment by f41gh7** [comment]
An issue must be fixed [v0.34.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.34.0) release.

**Comment by SaschaP95** [comment]
I tested it and it works.
We need to deploy the vmoperator and all roles/rolebindings in each namespace but it works.

I would like to thank you very much for the quick solution.

**Comment by f41gh7** [comment]
related issue https://github.com/VictoriaMetrics/operator/issues/653

**Comment by f41gh7** [comment]
Operator now correctly works at single namespace.
