### ISSUE TITLE
vmnodescrape-selector invalid 

### ISSUE THREAD

**Issue by 15234660879** [VictoriaMetrics/operator#645]
### Describe the bug

vmnodescrape-selector select master node invalid by node-role.kubernetes.io/master: ''
![image](https://user-images.githubusercontent.com/63493969/234753434-f6d95503-23eb-4b03-b2eb-c6f7df323e26.png)

### To Reproduce

  selector:
    matchLabels:
       node-role.kubernetes.io/master: ''

### Version

vmcluster-1.89.1

### Logs

no error log

**Comment by f41gh7** [comment]
An issue must be fixed [v0.34.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.34.0) release
