### ISSUE TITLE
VM operator aborts processing CRDs mid-way

### ISSUE THREAD

**Issue by sachinm24** [VictoriaMetrics/operator#648]
I'm using victoriametrics-operator to manage vmagents on kubernetes cluster. I have servicemonitor->vmservicescrape conversion enabled in all namespace.
If a servicemonitor config is not correct, VM operator aborts processing in the middle. So, if it discovered servicemonitors A, B, C, D and found an issue like missing field/incorrect field type in servicemonitor C, it aborts and does not create vmservicescrape for servicemonitor D.

This has serious implications -- a single incorrect service monitor can disable metrics scraping for many other important targets in the cluster. We also suspect that it removes the original vmservicescrape created from servicemonitor D

**Comment by f41gh7** [comment]
Hello,  it shouldn't happen in any case. Operator must skip broken ServiceMonitor processing, log error and move to the next object. Need to investigate this case. Could you provide some operator logs with errors?

 Also, it doesn't delete any ServiceMonitors or PodMonitors. It's responsibility of cluster administrator. 


 Only one possible case, when operator creates VMServiceScrape from ServiceMonitor and it contains some incorrect configuration (like missing secret reference). Operator may stop processing config generation for `VMAgent`. This issue must be addressed and fixed at the next release.

**Comment by f41gh7** [comment]
Version v0.34.0 contains a potential fix for this issue - it skips misconfigured scrape objects for `vmagent`.

**Comment by sachinm24** [comment]
> Version v0.34.0 contains a potential fix for this issue - it skips misconfigured scrape objects for `vmagent`.

thanks, we are currently using v0.20.1 currently. Will try it with upgrade

**Comment by hagen1778** [comment]
Closing as stale. Feel free to re-open
