### ISSUE TITLE
vmagent broken in helm chart v0.21.0 - `gunzip: /etc/vmagent/config/config.yaml: No such file or directory ` 

### ISSUE THREAD

**Issue by FrederikNS** [VictoriaMetrics/operator#649]
I just updated to v0.21.0 of this operator helm chart.

I'm using these values:

    operator:
      prometheus_converter_add_argocd_ignore_annotations: true
      psp_auto_creation_enabled: false
      enable_converter_ownership: true
      useCustomConfigReloader: true
    rbac:
      pspEnabled: false

And subsequently creating a VMAgent instance with the following spec:

    apiVersion: operator.victoriametrics.com/v1beta1
    kind: VMAgent
    metadata:
      name: vmagent
    spec:
      selectAllByDefault: true
      remoteWrite:
      - url: "http://vmsingle-vmsingle:8429/api/v1/write"
      resources:
        requests:
          cpu: 10m

This results in the VMAgent init-container `config-init` failing with the error message:

    gunzip: /etc/vmagent/config/config.yaml: No such file or directory

By having a look at the files in that directory, I can see that there is indeed a `/etc/vmagent/config/vmagent.yaml.gz` file, but no `/etc/vmagent/config/config.yaml` file.

The command for the init container is:

    /bin/sh -c gunzip -c /etc/vmagent/config/config.yaml > /etc/vmagent/config_out/vmagent.env.yaml

Which will obviously fail.

I can see that in previous versions of the operator, the config.yaml file was indeed present, but not gzipped. So I think this is a matter of mixing up some filenames as the gzip compression was implemented.

**Comment by FrederikNS** [comment]
Ah, I just forgot that I also reported it here:

https://github.com/VictoriaMetrics/operator/issues/619#issuecomment-1546749300

This seems to have been fixed already, and will be resolved in the next patch release according to @f41gh7

**Comment by f41gh7** [comment]
An issue must be fixed [v0.34.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.34.0) release
