### ISSUE TITLE
Wrong path for secrets and configs mount in api docs

### ISSUE THREAD

**Issue by VVvKamper** [VictoriaMetrics/operator#66]
Hello,

In the [api docs](https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmagentspec) mentioned that secrets and configmaps for vmagent is mounted to `/etc/vmagent/secrets` and /etc/vmagent/configs` but they are mounted to `/etc/vm/secrets` and `/etc/vm/configs` instead. 

Not sure if it's the bug in operator or in the docs so not i'm proposing any PR.

**Comment by f41gh7** [comment]
Good catch, thx. 

 It's a doc bug, I'll fix it.  All mount paths was unified and i forgot update doc.

 But it could cause a problem with converted resources. If you have  `VMAgent`  with premounted tlsConfig and define `Certfile`,`CAFile` and `Keyfile` defined as `/etc/prometheus/...` path at ServiceMonitor, after conversion it will be the same and it will lead to improper configuration.

**Comment by VVvKamper** [comment]
Yep, i'm already faces this problem. I'm just changed path in `prometheus-operator` chart values.

Also there is `additionalArgs` in full example of vmagent in release archive but the right key is `extraArgs`.

**Comment by f41gh7** [comment]
I'll add path replacement during api conversion, i guess it solves such problems. 

> Also there is `additionalArgs` in full example of vmagent in release archive but the right key is `extraArgs`.

 Thx, need to fix it as well.

**Comment by f41gh7** [comment]
Must be fixed at [v0.1.2](https://github.com/VictoriaMetrics/operator/releases/tag/v0.1.2)

docker image - victoriametrics/operator:v0.1.2
