### ISSUE TITLE
VMAgent Init Container Custom Image Not Working.

### ISSUE THREAD

**Issue by saithejareddy** [VictoriaMetrics/operator#660]
Hi Team,

We were trying to use a custom image for our init containers. Our Environment is a closed one. We can't use public images.
I have gone through the CRD's. Not able to understand why containers having patch but init containers not?

`              initContainers:
                description: 'InitContainers allows adding initContainers to the pod
                  definition. Those can be used to e.g. fetch secrets for injection
                  into the vmagent configuration from external sources. Any errors
                  during the execution of an initContainer will lead to a restart
                  of the Pod. More info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
                  Using initContainers for any use case other then secret fetching
                  is entirely outside the scope of what the maintainers will support
                  and by doing so, you accept that this behaviour may break at any
                  time without notice.'
                items:
                  description: A single application container that you want to run
                    within a pod.
                  required:
                  - name
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array`

`              containers:
                description: Containers property allows to inject additions sidecars
                  or to patch existing containers. It can be useful for proxies, backup,
                  etc.
                items:
                  description: A single application container that you want to run
                    within a pod.
                  required:
                  - name
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array`

![image](https://github.com/VictoriaMetrics/operator/assets/50693675/8e3fddd6-ee4e-45bf-9898-8a8ea28e1382)
![image](https://github.com/VictoriaMetrics/operator/assets/50693675/dc877dbd-309d-454f-94b9-6e5c51de2444)

**Comment by Haleygo** [comment]
@saithejareddy According to the error message, it's not a image problem, it failed because deployment got two init containers both named "config-init". 
Can you check the full vmagent yaml in your environment, see if duplicate initContainers are defined?

**Comment by saithejareddy** [comment]
Hi @Haleygo, I wanted to use custom docker image instead of the default one for init Containers. How to achieve that?

Note: We were able to do that for containers.

**Comment by saithejareddy** [comment]
Hey. Noticed that this issue got fixed in the latest version v0.34.1.
