### ISSUE TITLE
disable PSP on a running k8s cluster < 1.25

### ISSUE THREAD

**Issue by frankconrad** [VictoriaMetrics/operator#663]
In prepare to update to 12.5,... we need to remvoe all PodSecurityPolicy

Which change config to:
operator.psp_auto_creation_enabled: false
There still the generated PSP.
The ty to remove it via kubectl dleete psp ... hangs forever. As you have an finalizer and there is blocking it.

Best would be that in case disable PSP you make sure that any eventualy before generated PSP get removed.

We use vmagent, vmalert and vmcluster and all 3 have same issue.

The code look like only take care of create node delete

**Comment by zekker6** [comment]
@f41gh7 @Amper Could you please take a look?

**Comment by Haleygo** [comment]
@frankconrad Hi, what operator version do you use?
>There still the generated PSP.

You mean those psp already generated are still there, right? 
Turn off `psp_auto_creation_enabled` won't let operator clean psp created before, but stop creating new psp when new vmalert/vmagent/vmcluster applied.
So can you try delete the old vmalert/vmagent/vmcluster resources to let the operator do the cleanup thing and recreate them.

**Comment by Haleygo** [comment]
@frankconrad Hi, what operator version do you use?
>There still the generated PSP.

You mean those psp already generated are still there, right? 
Turn off `psp_auto_creation_enabled` won't let operator clean psp created before, but stop creating new psp when new vmalert/vmagent/vmcluster applied.
So can you try delete the old vmalert/vmagent/vmcluster resources to let the operator do the cleanup thing and recreate them.

**Comment by frankconrad** [comment]
I use victoria-metrics-operator chart 0.23.1
which use operator v0.34.1

yes there are still there
But I can't delete them, kubectl hangs

**Comment by frankconrad** [comment]
On a prodcution system you can't delete them...
I think there should be an better handling on operator side.
Remove finalizer is a hack.

**Comment by f41gh7** [comment]
> In prepare to update to 12.5,... we need to remvoe all PodSecurityPolicy
> 
> Which change config to: operator.psp_auto_creation_enabled: false There still the generated PSP. The ty to remove it via kubectl dleete psp ... hangs forever. As you have an finalizer and there is blocking it.
> 
> Best would be that in case disable PSP you make sure that any eventualy before generated PSP get removed.
> 
> We use vmagent, vmalert and vmcluster and all 3 have same issue.
> 
> The code look like only take care of create node delete

 Hello, it should be no problem with exist PSP objects and you shouldn't delete it. Kubernetes will remove it automatically.

 It's a nice feature to clean-up no longer used resources. Such as PSP,HPA, additionalServices, auto-created serviceScrape. Probably operator has to store features state at annotations and correctly delete it.

**Comment by Amper** [comment]
Done at [v0.36.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.36.0) release
