### ISSUE TITLE
support default ClusterIP vm-select service creation

### ISSUE THREAD

**Issue by eriksywu** [VictoriaMetrics/operator#687]
I might be missing context but I'm curious why does the `VMCluster` controller default to [creating](https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/vmcluster.go#L184) a headless service for `vm-select`? Does it make sense to include a mechanism to override the default `serviceSpec` to any arbitrary service type instead of having to create an additional service?

I've an application with a custom etc/resolv.conf that doesn't talk to kube-dns and requires a single proxy ip for prometheus.

**Comment by Haleygo** [comment]
Hello! VM operator won't create headless service for vminsert and the code you attached is for vmselect. So operator will create headless services for vmselect and vmstorage to help build command-line flags, like here
https://github.com/VictoriaMetrics/operator/blob/f2b8cf701a33f91cef19848c857fd6efb7db59dd/controllers/factory/vmcluster.go#L743-L747
It's necessary to make sure component like vminsert can specify every storage node address in cluster.

>I've an application with a custom etc/resolv.conf that doesn't talk to kube-dns 

You can try add some [dnsConfig](https://docs.victoriametrics.com/operator/api.html?highlight=dnsConfig) under those components.

**Comment by Haleygo** [comment]
> Hey @Haleygo sorry I meant `vm-select` not `vm-insert`. I think the default operator behaviour is to create a headless service for `vm-select` which I don't quite understand the reasoning for.

Yeah, vmselect headless sevice is needed to build `-selectNode=` arg, which is used to propagate cache reset request between vmselect nodes after [deletes time series](https://docs.victoriametrics.com/url-examples.html?highlight=tsdb/delete_series#apiv1admintsdbdelete_series).
