### ISSUE TITLE
[vmcluster]:  About the `HasSpecChanges` method and the `AnnotationsFiltered` method

### ISSUE THREAD

**Issue by z-anshun** [VictoriaMetrics/operator#753]
Hi, everyone!
When I read the source code, I had some doubts about `vmcluster`, they may be bugs:
1. The `HasSpecChanges` method does not judge null values, which may cause an error when querying crd for the first time.
code:
https://github.com/VictoriaMetrics/operator/blob/master/api/v1beta1/vmcluster_types.go#L947
error:
```
1.6944398628889349e+09  ERROR   controller      failed to check if cluster spec changed {"Request.Namespace": "vm", "Request.Name": "example-vmcluster-persistent", "error": "cannot parse last applied cluster spec value:  : unexpected end of JSON input"}
...
```

2. [annotationFilterPrefixes](https://github.com/VictoriaMetrics/operator/blob/master/api/v1beta1/additional.go#L44C1-L44C1) will filter annotations prefixed by `operator.victoriametrics.com/`, but in the [LastAppliedSpecAsPatch](https://github.com/VictoriaMetrics/operator/blob/master/api/v1beta1/vmcluster_types.go#L937) function, the key of annotation is set to `operator.victoriametrics/last-applied-spec`. I think `annotationFilterPrefixes` expects to filter it out.

**Comment by Haleygo** [comment]
Hmm, that's right. But there is no pods or other resources for vmcluster to wait or show it's ready, I can only come up the idea to have a hardcode timeout or recheck it's spec, both sound not so good. 
Please let me know if you get other idea)

**Comment by f41gh7** [comment]
Linked commit must remove misleading error message.

**Comment by f41gh7** [comment]
Fix included into the https://github.com/VictoriaMetrics/operator/releases/tag/v0.39.0 release
