### ISSUE TITLE
How to upgrade from 0.16 to v0.38

### ISSUE THREAD

**Issue by hkmdxlftjf** [VictoriaMetrics/operator#765]
hello, I'm using the 0.16 version of the operator, if i want upgrade to 0.38, will it affect existing vmclusters?

**Comment by Haleygo** [comment]
Hello!
It's a very big version jump, please check changelogs [here](https://github.com/VictoriaMetrics/operator/releases), there may contain some breaking change or field change for vmcluster. I'd recommend to do some tests in test env first.

**Comment by f41gh7** [comment]
Upgrade should be safe. There is no major breaking changes at API. 

 But it'll restart vmcluster pods, be ready for it.

 Also, check that vmcluster CRD object has `image.tag` defined. Otherwise operator'll upgrade cluster version to the latest default value.

**Comment by hkmdxlftjf** [comment]
Thank you for your reply, but what should I do for this update?

Is it possible to execute `kubectl apply -f crds/` and `kubectl apply -f operator/` to update

**Comment by hkmdxlftjf** [comment]
> Upgrade should be safe. There is no major breaking changes at API.
> 
> But it'll restart vmcluster pods, be ready for it.
> 
> Also, check that vmcluster CRD object has `image.tag` defined. Otherwise operator'll upgrade cluster version to the latest default value.

Thanks for your reply, but what should I do for this update?

Is it possible to execute kubectl apply -f crds/ and kubectl apply -f operator/ to update
