### ISSUE TITLE
VMAgent RBAC example file out of sync?

### ISSUE THREAD

**Issue by Z3po** [VictoriaMetrics/operator#768]
Hello everyone!

We're currently in the process of giving VictoriaMetrics a try as a replacement for our prometheus instances.
While installing the components and following the docs for it we've been confused about the RBAC rules necessary to run the `VMAgent`.

According to the documentation the example files in https://github.com/VictoriaMetrics/operator/blob/master/config/examples/vmagent_rbac.yaml shall be used to setup everything necessary. Now there's an odd resource called `app` I never heard about...is that just a typo?

Additionally this file seems to be off (probably an old version?) to the real needs as defined in the operator (see [here](https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/vmagent/rbac.go#L56-L112)). 

Can you please let us know which clusterwide RBAC rules are necessary to run the VMAgent? I guess the ones from the operator, no?

Thanks for your help and for building and maintaining this great piece of metric storage!

**Comment by f41gh7** [comment]
Hello, thx for reporting. It seems to be an issue with RBAC generation. For some reason `app` included incorrectly to the annotations, that generates RBAC access file.

**Comment by f41gh7** [comment]
Fix included into the https://github.com/VictoriaMetrics/operator/releases/tag/v0.39.0 release

**Comment by Z3po** [comment]
Thanks for taking care!\
Anything about the other question?\
The example RBAC file defines different needs than what the clusteroperator would set....
