### ISSUE TITLE
Custom reloader init containers cannot start in vmauth and vmagent pods

### ISSUE THREAD

**Issue by ebensom** [VictoriaMetrics/operator#770]
The PR https://github.com/VictoriaMetrics/operator/pull/667 introduced using custom reloader init containers for vmauth and vmagent to initialize the configuration. 
However there is a bug in the PR blocking the init containers to execute properly:

```
flag provided but not defined: -mode
v0.38.0
``` 

The config-reloader application introduced the `--only-init-config` for the initialization scenario (i.e. to exit from waiting for subsequent events during watcher initialization), however the vm-operator factory code uses `--mode=one-shot` argument.

**Comment by f41gh7** [comment]
Fix included to the https://github.com/VictoriaMetrics/operator/releases/tag/v0.39.0 release
