### ISSUE TITLE
vmselect does not allow federate metrics when one fo storage node is down

### ISSUE THREAD

**Issue by gasgurda** [VictoriaMetrics/operator#778]
### Describe the bug

When one of the nodes unavailable, scraping metrics doesn't work vi federate:
"...cannot export federated metrics, because some of vmstorage nodes are unavailable"
I have vmstorage cluster with 3 storage nodes
replicationFactor - 2

vmstorage should not stop serving federate requests when one storage node unavailable

### To Reproduce

Stop one storage node. Make a federate request

### Version

v1.93.1
v1.93.5

**Comment by hagen1778** [comment]
@gasgurda starting from [v0.39.1](https://github.com/VictoriaMetrics/operator/releases/tag/v0.39.1) operator should support passing replication factor to vmselects.
