### ISSUE TITLE
Operatorhub still at v0.33.0

### ISSUE THREAD

**Issue by clementmartin** [VictoriaMetrics/operator#792]
Hello,

We are using the operator in our OpenShift clusters, deployed via the operatorhub but I see that we are still are version 0.33.0 of the operator image. Is it expected ?

What is the maintenance / upgrades policy of the vm-operator at operatorhub.io 

Would we be better to deploy the operator by ourselves using argoCD and handle upgrades "manually" instead of relying on the operator lifecycle management framework and automated operatorHub based upgrades ?

**Comment by Amper** [comment]
Hey @clementmartin.
We will soon come to releasing on operator hub. There were temporary difficulties with it.

**Comment by Haleygo** [comment]
Hey @clementmartin @Tiggel ,
the latest [0.39.4](https://operatorhub.io/operator/victoriametrics-operator) has been released.
Close it as completed, feel free to reopen if there is problem.

**Comment by f41gh7** [comment]
Thanks @Haleygo !
