### ISSUE TITLE
Hope to add ScrapeConfig CRD

### ISSUE THREAD

**Issue by linuxduduniao** [VictoriaMetrics/operator#803]
Related functions have been provided by Prometheus Operator 
[ScrapeConfig](https://prometheus-operator.dev/docs/user-guides/scrapeconfig/)

**Comment by f41gh7** [comment]
@Amper  @Haleygo  WDYT?

**Comment by Haleygo** [comment]
Yeah, I think we can implement it as a generic scrape configuration for all service discoveries.

**Comment by linuxduduniao** [comment]
Must support sharding for ScrapeConfig

**Comment by Haleygo** [comment]
> Must support sharding for ScrapeConfig

Can you elaborate here? You mean to shard targets from one scrape job to several vmagents?

**Comment by linuxduduniao** [comment]
For example, when reading the node_exporter address from consul, when there are many node_exporter instances, the pressure on a single vmagent will be great.

**Comment by linuxduduniao** [comment]
> > Must support sharding for ScrapeConfig
> 
> Can you elaborate here? You mean to shard targets from one scrape job to several vmagents?

For example, when reading the instances address from consul (node_exporter, icmp, applications deployed on virtual machines), when there are many instances,  I need to use sharding to solve a single vmagent performance issue.

**Comment by linuxduduniao** [comment]
I want deploy vmagents on Kubernetes, these vmagents scrape all targets within the cluster(by apiserver) and outside the cluster(consul or http api).

**Comment by linuxduduniao** [comment]
I want deploy vmagents on Kubernetes, these vmagents scrape all targets within the cluster( serverMonitor, podMonitor ...) and outside the cluster(scrapeConfig).  Management CRD configuration by gitops (argocd + gitlab)

**Comment by linuxduduniao** [comment]
> This is already implemented on vmagent by `shardCount`, see https://new.docs.victoriametrics.com/operator/resources/vmagent/?highlight=shardcount#sharding. ScrapeConfig CRD will be a config resource like other scrape CRDs, help generating scrape_config file.

Thanks.  Because prometheus operator not support sharding for ScrapeConfig , so I wanted vm operator support sharding for ScrapeConfig

**Comment by f41gh7** [comment]
Must be fixed at [v0.43.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.43.0) release 

 Operator now supports ScrapeConfig and implements own version with VMScrapeConfig
