### ISSUE TITLE
Unknown usage of VMServiceScrape included in kustomize

### ISSUE THREAD

**Issue by tumd** [VictoriaMetrics/operator#809]
Hi,

The file [config/prometheus/monitor.yaml](https://github.com/VictoriaMetrics/operator/blob/388745c12f15d8d65ecc527cba39b7116ecf2109/config/prometheus/monitor.yaml) is included when [installing by kustomize](https://docs.victoriametrics.com/operator/setup.html#installing-by-kustomize). But I fail to understand what this specific VMServiceScrape-manifest is good for. At least it's not matching anything in any of my GKE or k3s clusters.

To me it looks like something legacy that probably should not be included in a clean install of the operator.
Or am I missing something?

**Comment by tumd** [comment]
On a related note, why is `namePrefix` specified in the [default kustomize target](https://github.com/VictoriaMetrics/operator/blob/388745c12f15d8d65ecc527cba39b7116ecf2109/config/default/kustomization.yaml#L95)?
IMHO this should not be specified here, and should instead be up to the user to set, if desired.

**Comment by f41gh7** [comment]
Hello, 
 I think kustomize config is outdated and not tested properly. We recommend to use helm for operator deployment. 

 Feel free to open PR with fixes for kustomize.

**Comment by f41gh7** [comment]
@AndrewChubatiuk  PTAL, close issue if it's no longer relevant.

**Comment by AndrewChubatiuk** [comment]
It was removed in v0.46
