### ISSUE TITLE
Confusing Kubernetes compatibility

### ISSUE THREAD

**Issue by der-ali** [VictoriaMetrics/operator#819]
The [Helm charts page](https://github.com/VictoriaMetrics/helm-charts/tree/master#kubernetes-compatibility-versions) states that the charts including the victoria-metrics-operator chart are compatiple with K8s versions 1.23 till 1.27. On the other hand, the operator's [README](https://github.com/VictoriaMetrics/operator#kubernetes-compatibility-versions) states that it's compatible with K8s versions 1.17 to 1.25.

Is the operator compatible with K8s 1.27? If so, will it always be compatible with the "K8s latest version - 1" ?

**Comment by Haleygo** [comment]
>Is the operator compatible with K8s 1.27?

Yes, operator should work with all the version since k8s 1.23, latest included. But we don't updating the doc very often(

So if you find any problem that opeartor doesn't work with latest version, please create an issue.

**Comment by Haleygo** [comment]
Support version been updated in https://github.com/VictoriaMetrics/operator/commit/e7c8f97e1d5d6152e3cc80961540b91a83dc9a73#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5.
>operator tested at kubernetes versions
from 1.25 to 1.28
