### ISSUE TITLE
Add drop_src_path_prefix_parts option to TargetRef of VMUserSpec 

### ISSUE THREAD

**Issue by dnull88** [VictoriaMetrics/operator#823]
VMAuth service can work with config parameter `drop_src_path_prefix_parts` but this option **absent in TargetRef of VMUserSpec** crd. 

It will allow use multiple endpoints of same services (for example vminsert) basing on url prefix as in example. ([different backends ](https://docs.victoriametrics.com/vmauth.html#generic-http-proxy-for-different-backends)

**Comment by ehuzii** [comment]
this is a very convenient setting that I miss as well

**Comment by f41gh7** [comment]
Was added as part of v0.40.0 release

**Comment by ehuzii** [comment]
I got error: `strict decoding error: unknown field "spec.unauthorizedAccessConfig[1].drop_src_path_prefix_parts"`
but in new docs this option availiable: https://docs.victoriametrics.com/operator/api/index.html#vmauthunauthorizedpath

**Comment by qveensi** [comment]
> > I got error: `strict decoding error: unknown field "spec.unauthorizedAccessConfig[1].drop_src_path_prefix_parts"` but in new docs this option availiable: https://docs.victoriametrics.com/operator/api/index.html#vmauthunauthorizedpath
> 
> Hello, make sure, that you have the latest vmauth image (v1.96.0)

most likely you forgot to add this option to the [crds.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/crd.yaml) for an object:VMAuth.VMAuthSpec.unauthorizedAccessConfig
