### ISSUE TITLE
why not feasible to deploy the VM Select as deployment as part of VMCluster 

### ISSUE THREAD

**Issue by SrinivasChilveri** [VictoriaMetrics/operator#841]
VM Select can be deployed as sts & deployment using helm charts but looks using operator can be deployed only as sts.

am i missing something or may i know the reason behind the same?

**Comment by f41gh7** [comment]
Hello,
  First of all, vmselect isn't stateless service. It has local disk cache for block processing and query response cache persistence during restarts.
 Also, with statefulset it's possible to access each pod by name, it's needed to cache invalidation and proper load-balancing. 
 vmselect must reset query response cache after series deleted request at one of pods. It performs broacast http call to the other pods.
 default k8s service loadbalacing is tcp connection based. It leads to the uneven load distribution between vmselect pods. With statefulset it's easy to use nginx or vmauth as http proxy in front of vmselect.
