### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/operator#85]
Improve readme:

- add uses cases.
- problems that operator may solve.
- difference between helm chart.
- troubleshooting.

**Comment by elmariofredo** [comment]
As discussed in #87 it would be nice to have extended CRD documentation. I have found this project we cloud probably use https://github.com/ahmetb/gen-crd-api-reference-docs

**Comment by f41gh7** [comment]
Yep, thanks. I'll take a look.

**Comment by f41gh7** [comment]
I've added few examples with -full prefix.  But i'm still not sure how to properly generate it from CRD definition. It becomes overloaded and not useful, plus there are a lot of special cases with embedded kubernetes objects.
