### ISSUE TITLE
api/vmrule: populate validation error in VMRule status

### ISSUE THREAD

**Issue by iceman2077** [VictoriaMetrics/operator#861]
### Is your feature request related to a problem? Please describe

When a user creates a VMRule and it is not the correct one, the user does not see the error.
I want the operator to write this error/status in the crd VMRule status in case of an error, and the user, when describing a resource, could see that there is an error there. Not all users have access to go and look at vmalert logs since this is a system component, and VMRule is just a user resourceю.

### Describe the solution you'd like

I want the operator to write this error in the crd VMRule status in case of an error, and the user, when describing a resource, could see that there is an error there.

**Comment by AndrewChubatiuk** [comment]
released in [v0.47.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.47.0)
