### ISSUE TITLE
Reconciliation Loop for Prometheus Converter

### ISSUE THREAD

**Issue by mirondeldev** [VictoriaMetrics/operator#869]
Current behavior of the `vmprometheusconverter` rely on Prometheus CRD `create` and `update` events, e.g.:
https://github.com/VictoriaMetrics/operator/blob/e261c37dc973154ff71073d7213000421416bd4e/controllers/vmprometheusconverter_controller.go#L86-L88

In some cases _(like manual or circumstantial deletion of custom resources)_ it leads to "orphaned" `Prometheus resources`.

So, the problem is **VictoriaMetrics Operator does not recreate converted VM-resources after ones being deleted**

#### Steps to reproduce 

* Create Prometheus resource, e.g. `PodMonitor`
  * Operator creates corresponding `PodScraper` resource
* Delete created `PodScraper` resource and keep original Prometheus `PodMonitor`
  * `PodScraper` resource will not be created until `PodMonitor` will be updated or recreated
  
**Would you please consider implementing reconciliation loop for `Prometheus resources` in `vmprometheusconverter`?**

**Comment by f41gh7** [comment]
Hello, it makes sense to me. And it'd be great to have an option to enable period reconciliation of prometheus watched objects.

**Comment by f41gh7** [comment]
Added new flag for period reconciliation at [v0.42.2 release](https://github.com/VictoriaMetrics/operator/releases/tag/v0.42.2)

 It accepts duration format, `-controller.prometheusCRD.resyncPeriod=10m`.

**Comment by mirondeldev** [comment]
@f41gh7 thx, much appreciated
