### ISSUE TITLE
Please update metricsql to a version > v0.68.0 or higher

### ISSUE THREAD

**Issue by bh-tt** [VictoriaMetrics/operator#873]
We tried using the drop_empty_series in a VMRule today, and the webhook returns a failure saying the function is unsupported. The function is question was added to metricsql parser over 3 months ago: https://github.com/VictoriaMetrics/metricsql/commit/768297e0918e52ee6b8b5802786484730bfed743. Could you please update the metricsql package version?

I'd be willing to submit a PR for this, though it is very very small.

**Comment by f41gh7** [comment]
Updated at main branch and ll be included to the next release.

 Current procedure for dependency upgrade is painful. Some packages aren't compatible with each other (thank you kubernetes), some don't work with go 1.22 (controller-gen).

**Comment by f41gh7** [comment]
Must be fixed at [v0.42.0 release](https://github.com/VictoriaMetrics/operator/releases/tag/v0.42.0)
