### ISSUE TITLE
VictoriaMetrics operator should be cgroup aware

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/operator#875]
[Go is not cgroup aware](https://github.com/golang/go/issues/33803). This means the VictoriaMetrics operator will be throttled hard in containerised environments with CPU limits.

The below screenshot shows the container with a CPU limit in Kubernetes. The first half of the time series is on a 13600k, with 20 threads. The second half is when the machine changed to use an EPYC 7763 with 128 threads.

![image](https://github.com/VictoriaMetrics/operator/assets/9749173/a300f5c4-0cf7-4b78-ad07-26194e754cfe)

[automaxprocs](https://github.com/uber-go/automaxprocs) can use cgroups automatically.

**Comment by Haleygo** [comment]
Hello @uhthomas ,
AFAIK the operator code itself doesn't use muti-thread to process resource objects, so I'm not sure the performance benefit here by setting `GOMAXPROCS`.  Did you see some good results with new `GOMAXPROCS`?

**Comment by f41gh7** [comment]
Hello, thanks for reporting the issue.

 Currently, operator doesn't use GOMAXPROCS for paralleling  CPU bound tasks. Actually, it doesn't perform any heavy CPU bound operations. And unlikely it will change in the future.

 Meanwhile the issue itself looks to me more like golang runtime problem, neither something that each application should fix on it's own.
