### ISSUE TITLE
Upgrade the controller runtime

### ISSUE THREAD

**Issue by cedericboersting** [VictoriaMetrics/operator#878]
Since the update 0.15 of the controller runtime there is a breaking change in the admission.Validator for the webhooks. 
The signature of this method added another return type. 

https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/webhook/admission/validator.go

The new signature is:
`ValidateCreate() (admission.Warnings, error)`

**Comment by f41gh7** [comment]
related issue https://github.com/VictoriaMetrics/operator/issues/859
