### ISSUE TITLE
suggestion: remove pods * permissions for vmagent controller 

### ISSUE THREAD

**Issue by ebensom** [VictoriaMetrics/operator#902]
It seems that the [`rbac:groups="",resources=pods,verbs=*`](https://github.com/VictoriaMetrics/operator/blob/de886759f741a50c148595645ad2c43a1599f571/controllers/vmagent_controller.go#L56) permission  is excessive and not being used by vm-operator.  
From K8S security point of view, it is advised to remove this permission if not needed, because a compromised vm-operator pod's SA has permission to create pods and exec into pods in all namespaces.

**Comment by Haleygo** [comment]
Hi @ebensom , operator does need delete permission to performing roll update for some service, check https://github.com/VictoriaMetrics/operator/pull/907#discussion_r1535391190.
And the role in examples should all be fixed in https://github.com/VictoriaMetrics/operator/pull/907.
