### ISSUE TITLE
can i convert scrape config to VMPodScrape cr?

### ISSUE THREAD

**Issue by hkmdxlftjf** [VictoriaMetrics/operator#923]
Hello, I would like to write code to convert existing configurations to VMPodScrape/VMNodeScrape. Is there any way to achieve this? Are there any codes that I can refer to? Thanks!

**Comment by Haleygo** [comment]
Hello!
Yes, vm-operator automatically convert existing Prometheus ServiceMonitor, PodMonitor, PrometheusRule, Probe and ScrapeConfig objects into corresponding VictoriaMetrics Operator objects by default. Check [this doc](https://docs.victoriametrics.com/operator/migration/) for details.
Code can be found in https://github.com/VictoriaMetrics/operator/blob/master/controllers/converter/apis.go.

**Comment by f41gh7** [comment]
Closing as stale. Feel free to re-open.
