### ISSUE TITLE
sync new vmauth config fields to vmauth&vmuser

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/operator#939]
vmauth unauthorized_user&vmuser are missing some new config fields like `src_query_args`, `discover_backend_ips`, need to sync with [upstream](https://docs.victoriametrics.com/vmauth/).

related https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6070

**Comment by f41gh7** [comment]
Changes included to the [v0.44.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.44.0) release
