### ISSUE TITLE
Question: support pause reconciliation for vmcluster cr

### ISSUE THREAD

**Issue by just1900** [VictoriaMetrics/operator#943]
Consider adding support for pause reconciliation for vmcluster cr, similar to what have been done in vmalertmanager
https://github.com/VictoriaMetrics/operator/blob/8f025b3b4fce6e3472cabaa49b07c748aa6e3ffa/api/victoriametrics/v1beta1/vmalertmanager_types.go#L151

This feature would be helpful when performing operational tasks. I am willing to submit a pull request if you are open to merging this change. @f41gh7

**Comment by Haleygo** [comment]
Sounds like a good feature to all the components.
But I don't see any related implementation for `VMAlertmanagerSpec.Paused` now, seems like a unfinished TODO.

**Comment by f41gh7** [comment]
Looks valuable feature to me. And good catch, currently `Paused` option is no-op for alertmanager.

**Comment by f41gh7** [comment]
Changes included to the [v0.44.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.44.0) release
