### ISSUE TITLE
Prepare a scratch/distroless release image for the VictoriaMetrics operator

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/operator#973]
It would be helpful to have those types of releases for the VictoriaMetrics operator

**Comment by Haleygo** [comment]
Scratch images are added in https://github.com/VictoriaMetrics/operator/pull/974, will be available since v0.46.0.

**Comment by f41gh7** [comment]
Operator uses distroless image since v0.46.0
