### ISSUE TITLE
RuleGroup: sync available config options with upstream

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/operator#982]
Looks like [rulegroup](https://docs.victoriametrics.com/operator/api/#rulegroup) is missing config options from the [upstream](https://docs.victoriametrics.com/vmalert/#groups):
1. [ eval_offset: <duration> ]
2. [ eval_delay: <duration> ]
3. [ eval_alignment: <bool> | default true]

**Comment by Haleygo** [comment]
New fields were added in [v0.46.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.46.0), close as completed.
